use super::docs_naming::{emit_type_doc_block, format_variant_lines, push_field_doc_lines};
use super::inventory::collect_declarations;
use super::model::{BANNER, ParsedType, SyntaxNodesGenReport, TypeKind};
use super::{BTreeSet, OsStr, Path, SYNTAX_NODES_MODULE_PREFIX, fs, syntax_helpers};

/// Write `Syntax/Nodes/*.bd`, `Syntax/Nodes.bd` barrel, `_inventory.txt`, and thin `Syntax.bd`.
pub fn emit_syntax_sdk(
    compiler_sdk_beskid_dir: &Path,
    analysis_src: &Path,
) -> Result<SyntaxNodesGenReport, std::io::Error> {
    let files = syntax_helpers::load_syntax_files(analysis_src)?;
    let helpers = syntax_helpers::build_helper_paths(&files);
    let (decls, skipped_generics) = collect_declarations(analysis_src, Some(&helpers))?;

    let syntax_dir = compiler_sdk_beskid_dir.join("Syntax");
    let nodes_dir = syntax_dir.join("Nodes");
    fs::create_dir_all(&nodes_dir)?;

    for hname in &helpers.helper_emit_order {
        if hname == "NodeList" {
            continue;
        }
        let body = if let Some(el_path) = helpers.list_helpers.get(hname) {
            syntax_helpers::emit_list_enum(hname, el_path)
        } else if let Some(inner_path) = helpers.opt_helpers.get(hname) {
            syntax_helpers::emit_optional_enum(hname, inner_path)
        } else {
            continue;
        };
        fs::write(nodes_dir.join(format!("{hname}.bd")), body)?;
    }

    let reflect_rs = analysis_src.join("compiler_sdk_reflect.rs");
    let traversal_names = crate::syntax_traversal::emit_traversal_sdk(&nodes_dir, analysis_src, &reflect_rs)?;

    let type_names: Vec<String> =
        decls.keys().filter(|k| !crate::syntax_traversal::is_host_only_type(k)).cloned().collect();

    for (name, parsed) in &decls {
        if crate::syntax_traversal::is_host_only_type(name) {
            continue;
        }
        let body = emit_type_bd(name, parsed);
        let mut out = String::new();
        out.push_str(BANNER);
        out.push('\n');
        out.push_str(&body);
        out.push('\n');
        let path = nodes_dir.join(format!("{name}.bd"));
        fs::write(path, out)?;
    }

    // `_inventory.txt` — one logical type name per line (sorted via BTreeMap iteration).
    let inv_path = nodes_dir.join("_inventory.txt");
    let inv_body = type_names.join("\n") + "\n";
    fs::write(inv_path, &inv_body)?;

    let mut barrel_names: Vec<String> = traversal_names.iter().cloned().collect();
    for h in &helpers.helper_emit_order {
        if h == "NodeList" || traversal_names.contains(h) {
            continue;
        }
        barrel_names.push(h.clone());
    }
    let mut extra: Vec<String> = decls
        .keys()
        .filter(|k| {
            !crate::syntax_traversal::is_host_only_type(k)
                && !helpers.helper_emit_order.iter().any(|h| h == *k)
                && !traversal_names.contains(*k)
        })
        .cloned()
        .collect();
    extra.sort();
    barrel_names.extend(extra);

    // Barrel: `Syntax/Nodes.bd`
    let mut barrel = String::new();
    barrel.push_str(BANNER);
    barrel.push('\n');
    for name in &barrel_names {
        barrel.push_str(&format!("pub mod {}.{};\n", SYNTAX_NODES_MODULE_PREFIX, name));
    }
    fs::write(syntax_dir.join("Nodes.bd"), barrel)?;

    // Thin `Syntax.bd` (no `ReflectStub` — lists / optionals are concrete under Syntax/Nodes/).
    let syntax_bd = r#"// CHECKED IN: regenerated by packages/compiler-sdk/regen_mod_sdk_surfaces.sh
// Rust sources in beskid_analysis are authoritative; nested shapes live under Syntax/Nodes/.

pub mod Beskid.Syntax.Nodes;

// Hand-maintained facade ------------------------------------------------------
// Immutable syntax node views for capture keys and typed emit construction (Mod SDK).
// Host supplies concrete trees; this package carries stable layout/version metadata only.

// Facade contract version aligned with platform-spec Beskid.Syntax hub.
pub string SyntaxFacadeVersion() {
    return "0.4.0";
}
"#
    .to_string();
    fs::write(compiler_sdk_beskid_dir.join("Syntax.bd"), syntax_bd)?;

    // Remove stale `*.bd` from prior generator runs (helper renames, mapping fixes).
    let mut expected_bd: BTreeSet<String> = traversal_names;
    expected_bd.extend(helpers.helper_emit_order.iter().filter(|&h| h != "NodeList").cloned());
    expected_bd.extend(decls.keys().filter(|&k| !crate::syntax_traversal::is_host_only_type(k)).cloned());
    for entry in fs::read_dir(&nodes_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension() != Some(OsStr::new("bd")) {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if !expected_bd.contains(stem) {
            fs::remove_file(&path)?;
        }
    }

    Ok(SyntaxNodesGenReport { type_names, skipped_generics, skipped_opaque_paths: Vec::new() })
}

pub(super) fn emit_type_bd(name: &str, parsed: &ParsedType) -> String {
    let doc = emit_type_doc_block(name, parsed);
    let decl = match parsed.kind {
        TypeKind::Struct => {
            if parsed.fields.is_empty() {
                format!("pub type {name} {{\n}}")
            } else {
                let mut lines: Vec<String> = Vec::new();
                for f in &parsed.fields {
                    push_field_doc_lines("    ", &f.rust_doc_lines, &mut lines);
                    lines.push(format!("    {} {},", f.beskid_ty, f.name));
                }
                format!("pub type {name} {{\n{}\n}}", lines.join("\n"))
            }
        }
        TypeKind::Enum => {
            let mut lines: Vec<String> = Vec::new();
            for v in &parsed.variants {
                push_field_doc_lines("    ", &v.rust_doc_lines, &mut lines);
                lines.extend(format_variant_lines(v));
            }
            format!("pub enum {name}\n{{\n{}\n}}", lines.join("\n"))
        }
    };
    doc + &decl
}
