pub(crate) const BANNER: &str = "// Generated by beskid_ast_reflect_gen (syntax nodes). Do not hand-edit.\n";

#[derive(Debug, Clone)]
pub struct SyntaxNodesGenReport {
    pub type_names: Vec<String>,
    pub skipped_generics: Vec<String>,
    pub skipped_opaque_paths: Vec<String>,
}
#[derive(Debug, Clone)]
pub struct ParsedType {
    pub kind: TypeKind,
    /// Relative path under `crates/beskid_analysis/src`, e.g. `syntax/expressions/pattern.rs`.
    pub source_rel_path: String,
    /// Rust `///` lines on the type (trimmed), in source order.
    pub rust_doc_lines: Vec<String>,
    /// Rust generic type parameter names (sorted) for `@par` emission; empty when non-generic.
    pub type_param_names: Vec<String>,
    pub fields: Vec<FieldMirror>,
    pub variants: Vec<EnumVariantMirror>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypeKind {
    Struct,
    Enum,
}

#[derive(Debug, Clone)]
pub struct FieldMirror {
    /// Beskid field / parameter name (camelCase where applicable).
    pub name: String,
    /// Rust-side identifier or slot label (e.g. `return_type`, `` `payload` `` tuple slot).
    pub rust_field_source: String,
    /// Beskid type written in generated `.bd` (qualified path, primitive, or `ReflectStub`).
    pub beskid_ty: String,
    /// When `beskid_ty` is `ReflectStub`, human-readable reason for Mod SDK consumers.
    pub stub_note: Option<String>,
    /// Rust `///` lines from the mirrored field when present. `ReflectStub` payloads get one trailing Mod SDK note.
    pub rust_doc_lines: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct EnumVariantMirror {
    pub name: String,
    /// Rust `///` lines on the variant. Its `@variant(…)` shape summary is emitted on the enclosing enum.
    pub rust_doc_lines: Vec<String>,
    pub shape: VariantShape,
}

#[derive(Debug, Clone)]
pub enum VariantShape {
    Unit,
    Tuple(Vec<FieldMirror>),
    /// Named fields inside the variant (rare in scanned syntax enums).
    Struct(Vec<FieldMirror>),
}
