use super::SemanticIssueKind;

impl SemanticIssueKind {
    pub fn code(&self) -> &'static str {
        match self {
            Self::DuplicateDefinitionName { .. } => "E1001",
            Self::DuplicateEnumVariant { .. } => "E1002",
            Self::DuplicateContractMethod { .. } => "E1003",
            Self::ConflictingEmbeddedContractMethod { .. } => "E1004",
            Self::UnknownTypeInDefinition { .. } => "E1005",
            Self::DuplicateItemName { .. } => "E1006",

            Self::AmbiguousImport { .. } => "E1104",
            Self::UnknownImportPath { .. } => "E1105",
            Self::UseBeforeDeclaration { .. } => "E1106",
            Self::InvalidSyntaxSpan { .. } => "E1151",
            Self::UnresolvedSyntaxValuePath => "E1152",
            Self::UnresolvedSyntaxTypePath => "E1153",
            Self::NonCanonicalSyntaxControlFlow { .. } => "E1154",
            Self::DuplicateAttributeDeclarationTarget { .. } => "E1508",
            Self::UnknownAttributeDeclarationTarget { .. } => "E1509",
            Self::AttributeTargetNotAllowed { .. } => "E1510",

            Self::VisibilityViolationImportPrivate { .. } => "E1501",
            Self::VisibilityModuleNotFound { .. } => "E1502",
            Self::FileScopedModuleNotFirstItem { .. } => "E1505",
            Self::DuplicateFileScopedModule { .. } => "E1506",
            Self::ModuleDeclarationForbiddenInFileScopedModule => "E1507",
            Self::ExtendTypePrivateMemberAccess { .. } => "E1511",
            Self::UnusedImport { .. } => "W1503",
            Self::UnusedPrivateItem { .. } => "W1504",

            Self::ContractMethodMissingImplementation { .. } => "E1601",
            Self::ContractImplementationSignatureMismatch { .. } => "E1602",
            Self::ContractMethodNotFound { .. } => "E1606",

            Self::ImmutableAssignment { .. } => "E1214",

            Self::MatchGuardMustBeBoolean => "E1308",
            Self::MatchArmTypeMismatch { .. } => "E1305",
            Self::MatchNonExhaustive { .. } => "E1304",
            Self::DuplicatePatternBinding { .. } => "E1306",
            Self::UnknownEnumPath { .. } => "E1301",
            Self::PatternArityMismatch { .. } => "E1307",
            Self::EnumConstructorArityMismatch { .. } => "E1302",
            Self::UnqualifiedEnumConstructor { .. } => "E1303",
            Self::BreakOutsideLoop => "E1401",
            Self::ContinueOutsideLoop => "E1402",
            Self::UnreachableCode => "W1403",

            Self::ResolveDuplicateItem { .. } => "E1102",
            Self::ResolveDuplicateLocal { .. } => "E1102",
            Self::ResolveUnknownValue { .. } => "E1101",
            Self::ResolveUnknownType { .. } => "E1201",
            Self::ResolveUnknownModulePath { .. } => "E1108",
            Self::ResolveUnknownValueInModule { .. } => "E1101",
            Self::ResolveUnknownTypeInModule { .. } => "E1201",
            Self::ResolveInvalidConformanceTarget { .. } => "E1607",
            Self::ResolvePrivateItemInModule { .. } => "E1107",
            Self::ResolveShadowedLocal { .. } => "W1103",

            Self::TypeUnknownType { .. } => "E1201",
            Self::TypeUnknownValueType => "E1201",
            Self::TypeUnknownStructType => "E1201",
            Self::TypeInvalidMemberTarget => "E1213",
            Self::TypeUnknownEnumType => "E1201",
            Self::TypeUnknownStructField { .. } => "E1211",
            Self::TypeUnknownEnumVariant { .. } => "E1301",
            Self::TypeMissingStructField { .. } => "E1212",
            Self::TypeMissingTypeAnnotation { .. } => "E1202",
            Self::TypeMissingTypeArguments => "E1203",
            Self::TypeGenericArgumentMismatch { .. } => "E1204",
            Self::TypeMismatch { .. } => "E1206",
            Self::TypeMatchArmMismatch { .. } => "E1305",
            Self::TypeCallArityMismatch { .. } => "E1204",
            Self::TypeCallArgumentMismatch { .. } => "E1205",
            Self::TypeEnumConstructorMismatch { .. } => "E1302",
            Self::TypeUnknownCallTarget => "E1606",
            Self::TypeInvalidBinaryOp => "E1209",
            Self::TypeInvalidUnaryOp => "E1210",
            Self::TypeNonBoolCondition => "E1208",
            Self::TypeUnsupportedExpression => "E1202",
            Self::TypeInvalidTryTarget => "E1222",
            Self::TypeInvalidEventInvocationScope => "E1219",
            Self::TypeInvalidEventCapacity => "E1220",
            Self::TypeInvalidEventSubscriptionTarget => "E1221",
            Self::SpawnTargetNotFiberCompatible => "E1223",
            Self::JoinWouldDeadlock => "E1224",
            Self::StackReferenceEscapesSpawn => "E1225",
            Self::AsyncKeywordReserved => "E1226",
            Self::AwaitKeywordReserved => "E1227",
            Self::TypeReturnMismatch { .. } => "E1207",
            Self::TypeNonIterableForTarget => "E1215",
            Self::TypeIterableNextArityMismatch { .. } => "E1216",
            Self::TypeIterableNextReturnNotOption => "E1217",
            Self::TypeIterableOptionSomeArityMismatch { .. } => "E1218",
            Self::TypeImplicitNumericCast { .. } => "W1203",

            Self::MacroUnknown { .. } => "E1901",
            Self::MacroArgumentArityMismatch { .. } => "E1902",
            Self::MacroArgumentKindMismatch { .. } => "E1903",
            Self::MacroMetavariableOutsideBody { .. } => "E1904",
            Self::MacroExpansionDepthExceeded { .. } => "E1905",
            Self::MacroAmbiguousName { .. } => "E1907",
            Self::MacroDuplicateParameter { .. } => "E1908",
            Self::QueryBoundsExceeded { .. } => "E1880",
            Self::QueryNodeSpanUnavailable => "E1881",
            Self::QueryPipelineConflict => "E1883",
            Self::QueryPipelineStaleGeneration => "E1884",

            Self::CompositionMissingLaunchHost => "E1701",
            Self::CompositionMultipleLaunchHosts => "E1702",
            Self::CompositionDependencyCycle { .. } => "E1703",
            Self::CompositionUnresolvedInject { .. } => "E1704",
            Self::CompositionAmbiguousInject { .. } => "E1705",
            Self::CompositionScopedOutsideWith => "E1706",
            Self::CompositionChildScopeWithoutParent { .. } => "E1707",
            Self::CompositionWithArgsMismatch { .. } => "E1708",
            Self::CompositionLaunchTargetNotHost { .. } => "E1709",
            Self::CompositionHostInheritanceCycle { .. } => "E1715",
            Self::CompositionDuplicateScopeName { .. } => "E1716",
            Self::CompositionHostInModProject => "E1710",
            Self::CompositionLaunchInLibProject => "E1711",
            Self::CompositionInjectOnConstructor => "E1712",
            Self::CompositionOverrideLifetimeMismatch { .. } => "E1713",
            Self::CompositionInvalidScopeQualifier { .. } => "E1714",

            Self::DocUnknownArgName { .. } => "W1610",
            Self::DocDuplicateArgName { .. } => "W1611",
            Self::DocArgOrReturnsOnNonCallable => "W1612",
            Self::DocReturnsOnUnit => "W1613",
            Self::DocUnknownDirective { .. } => "W1614",
            Self::DocUnresolvedRef { .. } => "W1615",
            Self::DocVariantOnNonEnum => "W1620",
            Self::DocUnknownVariantName { .. } => "W1621",
            Self::DocDuplicateVariantName { .. } => "W1622",
            Self::DocParWithoutGenerics => "W1623",
            Self::DocUnknownGenericName { .. } => "W1624",
            Self::DocDuplicateGenericName { .. } => "W1625",
            Self::RedundantEnumConstructorParens => "W1639",

            Self::NamingNotPascalCaseType { .. } => "W1630",
            Self::NamingNotPascalCaseVariant { .. } => "W1631",
            Self::NamingNotCamelCaseField { .. } => "W1632",
            Self::NamingNotPascalCaseCallable { .. } => "W1633",
            Self::NamingNotPascalCaseModuleSegment { .. } => "W1634",
            Self::NamingNotPascalCaseGeneric { .. } => "W1635",
            Self::NamingNotCamelCaseBinding { .. } => "W1636",
            Self::NamingNotSnakeCaseTest { .. } => "W1637",
            Self::NamingNotCamelCaseMacro { .. } => "W1638",
        }
    }
}
