//! ABI-surface checks for native composition.

use beskid_abi::{
    BUILTIN_SPECS, SYM_COMPOSITION_BIND_PLURAL, SYM_COMPOSITION_CONTAINER_CREATE, SYM_COMPOSITION_CONTAINER_DROP,
    SYM_COMPOSITION_LAUNCH, SYM_COMPOSITION_REGISTER, SYM_COMPOSITION_RESOLVE, SYM_COMPOSITION_RESOLVE_PLURAL,
    SYM_COMPOSITION_SCOPE_DEPTH, SYM_COMPOSITION_SCOPE_ENTER, SYM_COMPOSITION_SCOPE_LEAVE, SYM_COMPOSITION_SHUTDOWN,
};

#[test]
fn composition_builtin_symbols_are_registered() {
    let required = [
        SYM_COMPOSITION_CONTAINER_CREATE,
        SYM_COMPOSITION_CONTAINER_DROP,
        SYM_COMPOSITION_REGISTER,
        SYM_COMPOSITION_BIND_PLURAL,
        SYM_COMPOSITION_LAUNCH,
        SYM_COMPOSITION_SHUTDOWN,
        SYM_COMPOSITION_SCOPE_ENTER,
        SYM_COMPOSITION_SCOPE_LEAVE,
        SYM_COMPOSITION_RESOLVE,
        SYM_COMPOSITION_RESOLVE_PLURAL,
        SYM_COMPOSITION_SCOPE_DEPTH,
    ];
    for sym in required {
        assert!(BUILTIN_SPECS.iter().any(|spec| spec.symbol == sym), "BUILTIN_SPECS must list {sym}",);
        assert!(beskid_abi::RUNTIME_EXPORT_SYMBOLS.contains(&sym), "RUNTIME_EXPORT_SYMBOLS must list {sym}",);
    }
}
