[package]
name = "beskid_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
cranelift-codegen = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
gc-arena = { path = "../gc-arena" }
beskid_analysis = { path = "../beskid_analysis" }
beskid_abi = { path = "../beskid_abi" }
beskid_codegen = { path = "../beskid_codegen" }
beskid_pipeline = { path = "../beskid_pipeline" }
beskid_runtime = { path = "../beskid_runtime" }
anyhow = "1"

[features]
extern_dlopen = []

[dev-dependencies]
beskid_runtime = { path = "../beskid_runtime", features = ["metrics"] }
