ALTER TABLE pckg_packages
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'General',
    ADD COLUMN IF NOT EXISTS repository_url TEXT NULL,
    ADD COLUMN IF NOT EXISTS website_url TEXT NULL,
    ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN IF NOT EXISTS icon_url TEXT NULL;
