//! Canonical `corelib_tests` entry catalog shared by spine gates and parity scripts.

/// Every `corelib_tests` `.bd` entry guarded by front-end typecheck spine gates.
pub const CORELIB_TYPECHECK_ENTRIES: &[&str] = &[
    "system/SyscallWriteTests.bd",
    "system/SyscallApiTests.bd",
    "system/SyscallErgonomicsTests.bd",
    "system/OutputWriteLineTests.bd",
    "system/OutputWriteTests.bd",
    "console/AnsiEscapeTests.bd",
    "console/AnsiStyleChainTests.bd",
    "console/FormatMarkdownTests.bd",
    "console/AnsiSgrGoldenTests.bd",
    "console/ControlsPanelTests.bd",
    "console/ControlsProgressBarTests.bd",
    "console/ControlsLayoutTests.bd",
    "system/InputReadTests.bd",
    "system/ErrorWriteTests.bd",
    "core/ResultsTests.bd",
    "core/BytesTests.bd",
    "core/EncodingUtf8Tests.bd",
    "collections/ArrayTests.bd",
    "collections/CollectionsTier1Tests.bd",
    "collections/ListTests.bd",
    "collections/MapTests.bd",
    "collections/SetTests.bd",
    "collections/QueueTests.bd",
    "collections/StackTests.bd",
    "system/FsTests.bd",
    "system/PathTests.bd",
    "concurrency/ChannelApiTests.bd",
    "concurrency/MutexTryLockTests.bd",
    "concurrency/ConcurrencyClockTests.bd",
    "concurrency/HubRegisterTests.bd",
    "concurrency/WaitGroupTests.bd",
    "concurrency/FiberHandleTests.bd",
    "console/ConsoleMessageChannelTests.bd",
    "console/CapabilitiesTests.bd",
    "console/TerminalPlatformTests.bd",
    "console/ConsoleFacadeTests.bd",
    "console/FormatAttributesTests.bd",
    "console/FormatScanTests.bd",
    "console/ConsoleStyleTests.bd",
    "console/ControlsFrameTests.bd",
    "console/AnsiBuildersTests.bd",
    "console/RenderContextTests.bd",
    "text/TextCursorTests.bd",
    "text/TextParserTests.bd",
    "text/TextRegexTests.bd",
];

/// Fast local/CI-smoke subset (foundation + console + text parsing).
pub const CORELIB_TYPECHECK_SMOKE_ENTRIES: &[&str] = &[
    "core/ResultsTests.bd",
    "collections/ArrayTests.bd",
    "console/AnsiStyleChainTests.bd",
    "text/TextCursorTests.bd",
    "text/TextParserTests.bd",
];
