//! Host/runtime contract: C-layout string/array handles, builtin symbol names, and ABI version.

pub mod builtins;
pub mod symbols;
pub mod types;
pub mod version;

pub use builtins::{AbiParamKind, AbiReturnKind, BUILTIN_SPECS, BuiltinFnSpec};
pub use symbols::{
    BESKID_USER_FFI_LAYOUT_BAND, RUNTIME_EXPORT_SYMBOLS, SYM_ABI_VERSION, SYM_ALLOC,
    SYM_ARRAY_LEN, SYM_ARRAY_NEW, SYM_BESKID_REGISTER_CALLBACKS,
    SYM_CHANNEL_CLOSE, SYM_CHANNEL_CREATE, SYM_CHANNEL_RECEIVE, SYM_CHANNEL_RECEIVE_PTR,
    SYM_CHANNEL_RECEIVE_VALUE, SYM_CHANNEL_SEND, SYM_CHANNEL_SEND_PTR, SYM_CHANNEL_TRY_RECEIVE,
    SYM_CHANNEL_TRY_RECEIVE_PTR, SYM_CHANNEL_TRY_SEND, SYM_CHANNEL_TRY_SEND_PTR,
    SYM_COMPOSITION_BIND_PLURAL, SYM_COMPOSITION_CONTAINER_CREATE,
    SYM_COMPOSITION_CONTAINER_DROP, SYM_COMPOSITION_LAUNCH, SYM_COMPOSITION_REGISTER,
    SYM_COMPOSITION_RESOLVE, SYM_COMPOSITION_RESOLVE_PLURAL, SYM_COMPOSITION_SCOPE_DEPTH,
    SYM_COMPOSITION_SCOPE_ENTER, SYM_COMPOSITION_SCOPE_LEAVE, SYM_COMPOSITION_SHUTDOWN,
    SYM_DYNAMIC_CAST_CHECKED, SYM_DYNAMIC_CELL_CREATE, SYM_DYNAMIC_CELL_WRAP, SYM_DYNAMIC_MAP_AOT,
    SYM_DYNAMIC_MAP_FALLBACK, SYM_DYNAMIC_OBJECT_ALLOC,
    SYM_EVENT_GET_HANDLER, SYM_EVENT_LEN, SYM_EVENT_SUBSCRIBE, SYM_EVENT_UNSUBSCRIBE_FIRST,
    SYM_FIBER_CANCEL, SYM_FIBER_CURRENT_ID, SYM_FIBER_DETACH, SYM_FIBER_JOIN,
    SYM_FIBER_JOIN_VALUE, SYM_FIBER_NOW_MILLIS, SYM_FIBER_PROCESSOR_COUNT, SYM_FIBER_SPAWN,
    SYM_FIBER_SPAWN_WITH_CANCEL_SLOT, SYM_FIBER_YIELD, SYM_GC_BYTES_ALLOCATED, SYM_GC_COLLECT,
    SYM_GC_COLLECT_IF_NEEDED, SYM_GC_EXTERNAL_ROOT_COUNT, SYM_GC_OBJECT_COUNT, SYM_GC_PHASE,
    SYM_GC_REGISTER_ROOT, SYM_GC_ROOT_HANDLE, SYM_GC_UNREGISTER_ROOT, SYM_GC_UNROOT_HANDLE,
    SYM_GC_WRITE_BARRIER, SYM_HUB_CREATE, SYM_HUB_REGISTER, SYM_HUB_UNREGISTER,
    SYM_HUB_WAIT_RECEIVE, SYM_HUB_WAIT_RECEIVE_INDEX, SYM_HUB_WAIT_RECEIVE_VALUE,
    SYM_INTEROP_DISPATCH_PTR, SYM_INTEROP_DISPATCH_UNIT, SYM_INTEROP_DISPATCH_USIZE,
    SYM_MUTEX_CREATE, SYM_MUTEX_LOCK, SYM_MUTEX_TRY_LOCK, SYM_MUTEX_UNLOCK, SYM_PANIC,
    SYM_PANIC_STR, SYM_RUNTIME_PREEMPT_CHECK, SYM_STR_CONCAT, SYM_STR_EQ, SYM_STR_FROM_I64,
    SYM_STR_LEN, SYM_STR_NEW,
    SYM_SYSCALL_READ, SYM_SYSCALL_WRITE,
    SYM_TEST_BYTES_LEN, SYM_TEST_BYTES_PTR, SYM_WAIT_GROUP_ADD, SYM_WAIT_GROUP_CREATE,
    SYM_WAIT_GROUP_DONE, SYM_WAIT_GROUP_WAIT,
};
pub use types::{BeskidArray, BeskidStr};
pub use version::BESKID_RUNTIME_ABI_VERSION;
