//! Host/runtime contract: C-layout string/array handles, builtin symbol names, and ABI version.

pub mod abi_types;
pub mod abi_v5;
pub mod generated;
pub mod interop;
pub mod mod_contract;
pub mod runtime_kit;
pub mod runtime_provenance;
pub mod runtime_source;
pub mod serde_support;
pub mod toolchain;
pub mod types;
pub mod version;

pub use abi_types::{AbiParamKind, AbiReturnKind, BuiltinFnSpec};
pub use generated::builtins::BUILTIN_SPECS;

/// Every process-linked runtime builtin accepted by lowering and the JIT.
///
/// `BUILTIN_SPECS` is the remaining ABI-v4 transition table. ABI-v5-owned soft builtin rows are
/// generated from `runtime_manifest.bsol` and are intentionally appended here rather than copied
/// into that legacy snapshot.
pub fn all_builtin_specs() -> impl Iterator<Item = &'static BuiltinFnSpec> {
    BUILTIN_SPECS.iter().chain(generated::abi_v5_contract::ABI_V5_SOFT_BUILTINS.iter())
}
pub use generated::symbols::{
    BESKID_USER_FFI_LAYOUT_BAND, RUNTIME_EXPORT_SYMBOLS, SYM_ABI_VERSION, SYM_ALLOC, SYM_ARRAY_LEN, SYM_ARRAY_NEW,
    SYM_BESKID_REGISTER_CALLBACKS, SYM_BESKID_REGISTER_HANDLERS, SYM_BYTES_COMPARE, SYM_BYTES_COPY, SYM_BYTES_FROM_STR,
    SYM_BYTES_GET, SYM_BYTES_SET, SYM_CHANNEL_CLOSE, SYM_CHANNEL_CREATE, SYM_CHANNEL_RECEIVE, SYM_CHANNEL_RECEIVE_PTR,
    SYM_CHANNEL_RECEIVE_VALUE, SYM_CHANNEL_SEND, SYM_CHANNEL_SEND_PTR, SYM_CHANNEL_TRY_RECEIVE,
    SYM_CHANNEL_TRY_RECEIVE_PTR, SYM_CHANNEL_TRY_SEND, SYM_CHANNEL_TRY_SEND_PTR, SYM_CLOCK_MONOTONIC_NANOS,
    SYM_CLOCK_REALTIME_NANOS, SYM_COMPOSITION_BIND_PLURAL, SYM_COMPOSITION_CONTAINER_CREATE,
    SYM_COMPOSITION_CONTAINER_DROP, SYM_COMPOSITION_LAUNCH, SYM_COMPOSITION_REGISTER, SYM_COMPOSITION_RESOLVE,
    SYM_COMPOSITION_RESOLVE_PLURAL, SYM_COMPOSITION_SCOPE_DEPTH, SYM_COMPOSITION_SCOPE_ENTER,
    SYM_COMPOSITION_SCOPE_LEAVE, SYM_COMPOSITION_SHUTDOWN, SYM_DYNAMIC_CAST_CHECKED, SYM_DYNAMIC_CELL_CREATE,
    SYM_DYNAMIC_CELL_WRAP, SYM_DYNAMIC_MAP_AOT, SYM_DYNAMIC_MAP_FALLBACK, SYM_DYNAMIC_OBJECT_ALLOC, SYM_ENV_GET,
    SYM_ENV_GETCWD, SYM_ENV_SET, SYM_EVENT_GET_HANDLER, SYM_EVENT_LEN, SYM_EVENT_SUBSCRIBE,
    SYM_EVENT_UNSUBSCRIBE_FIRST, SYM_FIBER_CANCEL, SYM_FIBER_CURRENT_ID, SYM_FIBER_DETACH, SYM_FIBER_JOIN,
    SYM_FIBER_JOIN_VALUE, SYM_FIBER_NOW_MILLIS, SYM_FIBER_PROCESSOR_COUNT, SYM_FIBER_SPAWN,
    SYM_FIBER_SPAWN_WITH_CANCEL_SLOT, SYM_FIBER_YIELD, SYM_FS_DELETE, SYM_FS_EXISTS, SYM_FS_MKDIR, SYM_FS_READ_TEXT,
    SYM_FS_WRITE_TEXT, SYM_GC_BYTES_ALLOCATED, SYM_GC_COLLECT, SYM_GC_COLLECT_IF_NEEDED, SYM_GC_EXTERNAL_ROOT_COUNT,
    SYM_GC_OBJECT_COUNT, SYM_GC_PHASE, SYM_GC_REGISTER_ROOT, SYM_GC_ROOT_HANDLE, SYM_GC_UNREGISTER_ROOT,
    SYM_GC_UNROOT_HANDLE, SYM_GC_WRITE_BARRIER, SYM_HUB_CREATE, SYM_HUB_REGISTER, SYM_HUB_UNREGISTER,
    SYM_MUTEX_TRY_LOCK, SYM_MUTEX_UNLOCK, SYM_PANIC, SYM_PANIC_STR, SYM_PROCESS_EXIT, SYM_PROCESS_GETPID,
    SYM_RUNTIME_PREEMPT_CHECK, SYM_STR_CONCAT, SYM_STR_EQ, SYM_STR_FROM_BYTES_UTF8, SYM_STR_FROM_I64, SYM_STR_LEN,
    SYM_STR_NEW, SYM_STR_SLICE, SYM_SYSCALL_READ, SYM_SYSCALL_READ_BYTES, SYM_SYSCALL_WRITE, SYM_SYSCALL_WRITE_BYTES,
    SYM_TEST_BYTES_LEN, SYM_TEST_BYTES_PTR, SYM_TTY_WINSIZE, SYM_WAIT_GROUP_ADD, SYM_WAIT_GROUP_CREATE,
    SYM_WAIT_GROUP_DONE, SYM_WAIT_GROUP_WAIT,
};
pub use mod_contract::{
    ModAnalysisRequest, ModCatalog, ModCollectRequest, ModCollectTargetSet, ModCompilation, ModContractRegistration,
    ModContractRegistrationSlice, ModGeneratedSyntaxContribution, ModGenerationRequest, ModGeneratorEntryFn,
    ModPackage, ModPackageSlice, ModStrSlice, ModSyntaxContributionItem, ModSyntaxContributionSlice,
    ModSyntaxContributionTag, ModSyntaxNodeHandle, ModWorkspace, ModWorkspaceMember, ModWorkspaceMemberSlice,
};
pub use types::{BeskidArray, BeskidStr};
pub use version::BESKID_RUNTIME_ABI_VERSION;
