[package]
name = "beskid_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
beskid_abi = { path = "../beskid_abi" }
abfall = { path = "../abfall" }
slotmap = { workspace = true }
corosensei = { version = "0.3.3", default-features = true }

[build-dependencies]
beskid_manifest = { path = "../beskid_manifest" }

[dev-dependencies]
criterion = "0.5"

[features]
metrics = []
arrays_backing = [] # No-op since 2026-06-05: backing store is always allocated unconditionally.
sched = []

[[bench]]
name = "runtime_micro"
harness = false
