[package]
name = "beskid_cli"
version = "0.1.77"
edition = "2024"

[dependencies]
beskid_tools = { path = "../beskid_tools" }
beskid_aot = { path = "../beskid_aot" }
beskid_analysis = { path = "../beskid_analysis" }
beskid_queries = { path = "../beskid_queries" }
beskid_codegen = { path = "../beskid_codegen" }
beskid_pipeline = { path = "../beskid_pipeline" }
beskid_graph = { path = "../beskid_graph" }
beskid_engine = { path = "../beskid_engine" }
graphs-tui = { workspace = true }
beskid_pckg = { path = "../beskid_pckg" }
beskid_template = { path = "../beskid_template" }
beskid_lsp = { path = "../beskid_lsp" }
beskid_repl = { path = "../beskid_repl" }
tokio = { version = "1.48", features = ["rt-multi-thread"] }
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
miette = { version = "7.1", features = ["fancy"] }
pest = { workspace = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
argfile = "0.2"
semver = "1.0.27"
walkdir = "2"
