[package]
name = "beskid_isle"
version = "0.1.0"
edition = "2024"

[dependencies]
beskid_queries = { path = "../beskid_queries" }
cranelift-codegen = { workspace = true, features = ["arm64", "x86"] }
cranelift-frontend = { workspace = true }

[build-dependencies]
cranelift-isle = { workspace = true }

[dev-dependencies]
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
target-lexicon = "0.13"
