use std::fmt::Write as _;

use crate::model::{DispatchEntry, ManifestRoot};

const GENERATED_BANNER: &str = "// @generated by beskid_manifest from runtime_manifest.bsol — do not edit.";

pub(super) fn write_generated_preamble(out: &mut String, extra_allows: &[&str]) {
    writeln!(out, "{GENERATED_BANNER}").unwrap();
    for allow in extra_allows {
        writeln!(out, "#![allow({allow})]").unwrap();
    }
    writeln!(out).unwrap();
}

pub(super) fn dispatch_groups(manifest: &ManifestRoot) -> [&[DispatchEntry]; 4] {
    [&manifest.dispatch.usize, &manifest.dispatch.ptr, &manifest.dispatch.unit, &manifest.dispatch.i64]
}

pub(super) fn language_handler_beskid_path(entry: &DispatchEntry) -> Option<Vec<String>> {
    if !entry.is_language_handler() {
        return None;
    }
    let segments = entry
        .dispatch_key
        .split('_')
        .map(|segment| {
            let mut chars = segment.chars();
            chars.next().map_or_else(String::new, |first| first.to_uppercase().chain(chars).collect())
        })
        .collect::<Vec<_>>();
    Some(["Runtime", "Handlers"].into_iter().map(str::to_string).chain(segments).collect())
}

pub(super) fn dispatch_doc(manifest: &ManifestRoot, symbol: &str) -> Option<String> {
    for entry in manifest.kernel.iter() {
        if entry.symbol == symbol {
            return None;
        }
    }
    for group in dispatch_groups(manifest) {
        for entry in group {
            if entry.dispatch_key == symbol {
                return Some(format!("Dispatch routing key for tag `{}` ({})", entry.name, entry.dispatch_key));
            }
        }
    }
    None
}

pub(super) fn tag_const_name(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_uppercase() && !out.is_empty() {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

pub(super) fn symbol_const_suffix(symbol: &str) -> String {
    match symbol {
        "beskid_runtime_abi_version" => "ABI_VERSION".to_string(),
        "fiber_join_status" => "FIBER_JOIN".to_string(),
        "channel_receive_status" => "CHANNEL_RECEIVE".to_string(),
        "hub_wait_receive_status" => "HUB_WAIT_RECEIVE".to_string(),
        other => {
            other.chars().map(|ch| if ch.is_ascii_alphanumeric() { ch.to_ascii_uppercase() } else { '_' }).collect()
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash)]

pub(super) fn dispatch_tag_imports(manifest: &ManifestRoot) -> String {
    let mut tags = Vec::new();
    for group in dispatch_groups(manifest) {
        for entry in group {
            tags.push(format!("TAG_{}", tag_const_name(&entry.name)));
        }
    }
    tags.sort();
    tags.dedup();
    tags.join(", ")
}
