//! Beskid stub generation from Rust [`syn`] trees used in `beskid_analysis`.
//!
//! v1 emits structural placeholders (`ReflectStub`) suitable for golden tests
//! and `Beskid.Compiler.*` Mod SDK surfaces—not a semantic mapping.

#![forbid(unsafe_code)]

mod emit_idents;

pub mod syntax_nodes;

use std::collections::BTreeSet;
use std::ffi::OsString;
use std::fs;
use std::path::{Path, PathBuf};

use syn::{Attribute, Fields, Generics, Item, Visibility, parse_file};

use crate::emit_idents::escape_beskid_ident;

/// Default Rust sources under `beskid_analysis` (relative to the compiler workspace root).
pub const DEFAULT_ANALYSIS_ALLOWLIST: &[&str] = &[
    "crates/beskid_analysis/src/syntax/items/node.rs",
    "crates/beskid_analysis/src/hir/item.rs",
];

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GenOptions {
    /// When true, only items carrying `#[beskid_reflect]` are emitted.
    pub only_annotated: bool,
    /// When false, skips the standard generated banner comments.
    pub emit_banner: bool,
    /// When false, skips `pub type ReflectStub {}` (for stitching into larger files).
    pub emit_reflect_stub: bool,
    /// When set, only `pub enum` / `pub struct` items whose Rust identifier is listed are emitted.
    pub item_allowlist: Option<BTreeSet<String>>,
}

impl Default for GenOptions {
    fn default() -> Self {
        Self {
            only_annotated: false,
            emit_banner: true,
            emit_reflect_stub: true,
            item_allowlist: None,
        }
    }
}

#[derive(Debug)]
pub enum GenError {
    Io(std::io::Error),
    Parse { path: PathBuf, message: String },
}

impl std::fmt::Display for GenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GenError::Io(e) => write!(f, "{e}"),
            GenError::Parse { path, message } => {
                write!(f, "failed to parse {}: {message}", path.display())
            }
        }
    }
}

impl std::error::Error for GenError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            GenError::Io(e) => Some(e),
            GenError::Parse { .. } => None,
        }
    }
}

impl From<std::io::Error> for GenError {
    fn from(value: std::io::Error) -> Self {
        GenError::Io(value)
    }
}

/// Resolve default allowlist paths against `compiler_workspace_root` (directory containing the workspace `Cargo.toml`).
pub fn default_allowlist_paths(compiler_workspace_root: &Path) -> Vec<PathBuf> {
    DEFAULT_ANALYSIS_ALLOWLIST
        .iter()
        .map(|rel| compiler_workspace_root.join(rel))
        .collect()
}

fn generics_is_empty(generics: &Generics) -> bool {
    generics.params.is_empty()
}

fn item_name_allowed(name: &str, allowlist: &Option<BTreeSet<String>>) -> bool {
    match allowlist {
        None => true,
        Some(set) => set.contains(name),
    }
}

/// Generate deterministic Beskid source for the given Rust source files.
pub fn generate_from_paths(paths: &[PathBuf], options: &GenOptions) -> Result<String, GenError> {
    let mut out = String::new();
    if options.emit_banner {
        out.push_str("// Generated by beskid_ast_reflect_gen (v1 stubs). Do not hand-edit.\n");
        out.push_str(
            "// Target: future Beskid.Compiler.Syntax reflection; payloads are placeholders.\n\n",
        );
    }
    if options.emit_reflect_stub {
        out.push_str("pub type ReflectStub {}\n\n");
    }

    let mut paths_sorted = paths.to_vec();
    paths_sorted.sort();

    for path in paths_sorted {
        let src = fs::read_to_string(&path)?;
        let file = parse_file(&src).map_err(|e| GenError::Parse {
            path: path.clone(),
            message: e.to_string(),
        })?;
        let label = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("unknown.rs");
        out.push_str(&format!("// --- {label} ---\n\n"));
        out.push_str(&emit_file(&file.items, options));
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    Ok(out.trim_end().to_string() + "\n")
}

fn emit_file(items: &[Item], options: &GenOptions) -> String {
    let mut chunks = Vec::new();
    for item in items {
        if options.only_annotated && !item_has_beskid_reflect(item) {
            continue;
        }
        if let Some(s) = emit_item(item, options) {
            chunks.push(s);
        }
    }
    chunks.join("\n\n")
}

fn item_has_beskid_reflect(item: &Item) -> bool {
    let attrs = match item {
        Item::Enum(i) => &i.attrs,
        Item::Struct(i) => &i.attrs,
        _ => return false,
    };
    attrs.iter().any(is_beskid_reflect_attr)
}

fn is_beskid_reflect_attr(attr: &Attribute) -> bool {
    attr.path()
        .segments
        .last()
        .is_some_and(|s| s.ident == "beskid_reflect")
}

fn emit_item(item: &Item, options: &GenOptions) -> Option<String> {
    match item {
        Item::Enum(e) if matches!(e.vis, Visibility::Public(_)) => {
            if !generics_is_empty(&e.generics) {
                return None;
            }
            let name = e.ident.to_string();
            if !item_name_allowed(&name, &options.item_allowlist) {
                return None;
            }
            let mut variants = Vec::new();
            for v in &e.variants {
                variants.push(emit_enum_variant(v));
            }
            variants.sort();
            let body = variants.join("\n");
            Some(format!("pub enum {name}\n{{\n{body}\n}}"))
        }
        Item::Struct(s) if matches!(s.vis, Visibility::Public(_)) => {
            if !generics_is_empty(&s.generics) {
                return None;
            }
            let name = s.ident.to_string();
            if !item_name_allowed(&name, &options.item_allowlist) {
                return None;
            }
            Some(format!("pub type {name}\n{{\n}}"))
        }
        _ => None,
    }
}

fn tuple_variant_placeholder_names(count: usize) -> Vec<String> {
    match count {
        0 => Vec::new(),
        1 => vec!["payload".to_string()],
        n => (0..n).map(|i| format!("variant_field_{i}")).collect(),
    }
}

fn emit_enum_variant(v: &syn::Variant) -> String {
    let id = v.ident.to_string();
    match &v.fields {
        Fields::Unit => format!("    {id},"),
        Fields::Unnamed(uf) => {
            let names = tuple_variant_placeholder_names(uf.unnamed.len());
            let mut parts = Vec::new();
            for (i, _f) in uf.unnamed.iter().enumerate() {
                let n = names
                    .get(i)
                    .cloned()
                    .unwrap_or_else(|| format!("variant_field_{i}"));
                parts.push(format!("ReflectStub {n}"));
            }
            let inner = parts.join(", ");
            format!("    {id}({inner}),")
        }
        Fields::Named(nf) => {
            let mut parts = Vec::new();
            for f in &nf.named {
                let fname = f
                    .ident
                    .as_ref()
                    .map(|i| escape_beskid_ident(&i.to_string()))
                    .unwrap_or_else(|| "field".into());
                parts.push(format!("ReflectStub {fname}"));
            }
            let inner = parts.join(", ");
            format!("    {id}({inner}),")
        }
    }
}

/// Parsed CLI flags and optional source paths (paths may be empty until `--workspace` is applied).
pub fn parse_cli_args(args: &[OsString]) -> Result<CliInvocation, String> {
    let mut only_annotated = false;
    let mut emit_banner = true;
    let mut emit_reflect_stub = true;
    let mut item_allowlist: Option<BTreeSet<String>> = None;
    let mut out_path: Option<PathBuf> = None;
    let mut paths = Vec::new();
    let mut i = 0usize;
    while i < args.len() {
        let arg = args[i].to_string_lossy();
        match arg.as_ref() {
            "--only-annotated" => {
                only_annotated = true;
                i += 1;
            }
            "--no-banner" => {
                emit_banner = false;
                i += 1;
            }
            "--no-reflect-stub" => {
                emit_reflect_stub = false;
                i += 1;
            }
            "--items" => {
                let list = args
                    .get(i + 1)
                    .ok_or_else(|| "--items requires a comma-separated list".to_string())?
                    .to_string_lossy();
                let set: BTreeSet<String> = list
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
                if set.is_empty() {
                    return Err("--items list was empty".to_string());
                }
                item_allowlist = Some(set);
                i += 2;
            }
            "--out" => {
                let p = args
                    .get(i + 1)
                    .ok_or_else(|| "--out requires a path".to_string())?;
                out_path = Some(PathBuf::from(p));
                i += 2;
            }
            "--" => {
                i += 1;
                while i < args.len() {
                    paths.push(PathBuf::from(&args[i]));
                    i += 1;
                }
                break;
            }
            s if s.starts_with('-') => {
                return Err(format!("unknown flag: {s}"));
            }
            _ => {
                paths.push(PathBuf::from(&args[i]));
                i += 1;
            }
        }
    }
    Ok(CliInvocation {
        options: GenOptions {
            only_annotated,
            emit_banner,
            emit_reflect_stub,
            item_allowlist,
        },
        out_path,
        paths,
    })
}

pub struct CliInvocation {
    pub options: GenOptions,
    pub out_path: Option<PathBuf>,
    pub paths: Vec<PathBuf>,
}

pub fn run_cli(inv: CliInvocation) -> Result<(), GenError> {
    let generated = generate_from_paths(&inv.paths, &inv.options)?;
    let out = inv.out_path.or_else(|| {
        std::env::var_os("OUT_DIR").map(|d| {
            let mut p = PathBuf::from(d);
            p.push("ast_reflect");
            let _ = fs::create_dir_all(&p);
            p.push("generated.bd");
            p
        })
    });
    match &out {
        Some(p) => {
            if let Some(parent) = p.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(p, generated)?;
        }
        None => {
            print!("{generated}");
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn golden_fixture_enum_and_struct() {
        let fixture =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/mirror_reflect.rs");
        let options = GenOptions {
            only_annotated: true,
            ..Default::default()
        };
        let got = generate_from_paths(&[fixture], &options).expect("generate");
        let expected = include_str!("../tests/expected/mirror_reflect.generated.bd");
        assert_eq!(got, expected);
    }

    #[test]
    fn parses_allowlisted_analysis_node_rs() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let node_rs = root.join("crates/beskid_analysis/src/syntax/items/node.rs");
        if !node_rs.is_file() {
            return;
        }
        let options = GenOptions::default();
        let got = generate_from_paths(&[node_rs], &options).expect("parse node.rs");
        assert!(got.contains("pub enum Node"));
        assert!(got.contains("    Function(ReflectStub payload),"));
    }

    #[test]
    fn skips_generic_public_enum() {
        let src = "pub enum Foo<T> { A(T), }\n";
        let file = syn::parse_file(src).unwrap();
        let options = GenOptions::default();
        let got = emit_file(&file.items, &options);
        assert!(got.is_empty());
    }

    #[test]
    fn item_allowlist_filters_structs_and_enums() {
        let src = r#"
            pub enum Alpha { X, }
            pub struct Beta { x: u32, }
            pub enum Gamma { Y, }
        "#;
        let file = syn::parse_file(src).unwrap();
        let options = GenOptions {
            item_allowlist: Some(BTreeSet::from(["Gamma".to_string()])),
            ..Default::default()
        };
        let got = emit_file(&file.items, &options);
        assert!(got.contains("pub enum Gamma"));
        assert!(!got.contains("Alpha"));
        assert!(!got.contains("Beta"));
    }
}
