//! Per-type Beskid (`.bd`) emission for the syntax AST vocabulary in `beskid_analysis`.
//!
//! Scans `syntax/{items,types,expressions,statements,common}/**/*.rs`, emits one file per
//! `pub struct` / `pub enum` (skipping `mod.rs`, helpers, and generic items).

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use syn::{Attribute, Expr, Fields, GenericArgument, Item, Lit, Meta, PathArguments, Type, Visibility};

use crate::emit_idents::escape_beskid_ident;

const BANNER: &str = "// Generated by beskid_ast_reflect_gen (syntax nodes). Do not hand-edit.\n";

/// Relative directories under `crates/beskid_analysis/src` scanned for syntax surface types.
pub const SYNTAX_SCAN_SUBDIRS: &[&str] = &[
    "syntax/items",
    "syntax/types",
    "syntax/expressions",
    "syntax/statements",
    "syntax/common",
];

/// Files excluded from scanning (no `pub struct` / `pub enum` surface definitions).
pub const SYNTAX_SCAN_SKIP_FILES: &[&str] = &[
    "mod.rs",
    "parse_helpers.rs",
    "doc_attached_items.rs",
    // Span metadata (`SpanInfo`) is not a `NodeKind` / `ReflectSdkNodeKind` token; `Spanned<T>` is generic.
    "span.rs",
    // Parsed for lowering only; not part of the public AST `Node` / query classification surface.
    "impl_block.rs",
];

/// Module prefix for emitted node modules (under compiler-sdk `src/`).
pub const SYNTAX_NODES_MODULE_PREFIX: &str = "Beskid.Compiler.Syntax.Nodes";

/// Full Beskid path to the shared placeholder type (defined in `Syntax.bd`).
pub fn reflect_stub_path() -> &'static str {
    "Beskid.Compiler.Syntax.ReflectStub"
}

#[derive(Debug, Clone)]
pub struct SyntaxNodesGenReport {
    pub type_names: Vec<String>,
    pub skipped_generics: Vec<String>,
    pub skipped_opaque_paths: Vec<String>,
}

/// Discover all `pub struct` / `pub enum` names under the syntax scan dirs.
pub fn inventory_syntax_type_names(analysis_src: &Path) -> Result<Vec<String>, std::io::Error> {
    let (decls, _) = collect_declarations(analysis_src)?;
    Ok(decls.keys().cloned().collect())
}

fn collect_declarations(
    analysis_src: &Path,
) -> Result<(BTreeMap<String, ParsedType>, Vec<String>), std::io::Error> {
    let mut files = Vec::new();
    for sub in SYNTAX_SCAN_SUBDIRS {
        let dir = analysis_src.join(sub);
        if dir.is_dir() {
            collect_rs_files(&dir, &mut files)?;
        }
    }
    files.sort();

    let mut map = BTreeMap::new();
    let mut skipped_generics = Vec::new();
    for path in files {
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if SYNTAX_SCAN_SKIP_FILES.contains(&name) {
            continue;
        }
        let rel_path = path
            .strip_prefix(analysis_src)
            .ok()
            .and_then(|p| p.to_str())
            .map(|s| s.replace('\\', "/"))
            .unwrap_or_else(|| name.to_string());
        let src = fs::read_to_string(&path)?;
        let file = syn::parse_file(&src).map_err(|e| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("{}: {e}", path.display()),
            )
        })?;
        for item in &file.items {
            if let Some((ident, parsed)) =
                parse_top_level_item(item, true, &mut skipped_generics, rel_path.as_str())
            {
                map.insert(ident, parsed);
            }
        }
    }
    Ok((map, skipped_generics))
}

fn collect_rs_files(dir: &Path, out: &mut Vec<PathBuf>) -> std::io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let p = entry?.path();
        if p.is_dir() {
            collect_rs_files(&p, out)?;
        } else if p.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(p);
        }
    }
    Ok(())
}

#[derive(Debug, Clone)]
pub struct ParsedType {
    pub kind: TypeKind,
    /// Relative path under `crates/beskid_analysis/src`, e.g. `syntax/expressions/pattern.rs`.
    pub source_rel_path: String,
    /// First paragraph of Rust `///` / `//!` on the type, cleaned for one-line Beskid doc.
    pub rust_doc_summary: Option<String>,
    pub fields: Vec<FieldMirror>,
    pub variants: Vec<EnumVariantMirror>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypeKind {
    Struct,
    Enum,
}

#[derive(Debug, Clone)]
pub struct FieldMirror {
    pub name: String,
    pub beskind_ty: String,
    /// When `beskind_ty` is `ReflectStub`, human-readable reason for Mod SDK consumers.
    pub stub_note: Option<String>,
}

#[derive(Debug, Clone)]
pub struct EnumVariantMirror {
    pub name: String,
    pub rust_doc_summary: Option<String>,
    pub shape: VariantShape,
}

#[derive(Debug, Clone)]
pub enum VariantShape {
    Unit,
    Tuple(Vec<FieldMirror>),
    /// Named fields inside the variant (rare in scanned syntax enums).
    Struct(Vec<FieldMirror>),
}

fn doc_summary_from_attrs(attrs: &[Attribute]) -> Option<String> {
    let mut lines = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        let Meta::NameValue(nv) = &attr.meta else {
            continue;
        };
        let Expr::Lit(syn::ExprLit {
            lit: Lit::Str(s), ..
        }) = &nv.value
        else {
            continue;
        };
        let t = s.value().trim().replace('\n', " ");
        if !t.is_empty() {
            lines.push(t);
        }
    }
    if lines.is_empty() {
        return None;
    }
    Some(lines.join(" "))
}

fn unique_field_name(base: &str, used: &mut BTreeSet<String>) -> String {
    let esc = escape_beskid_ident(base);
    if !used.contains(&esc) {
        used.insert(esc.clone());
        return esc;
    }
    let mut i = 2u32;
    loop {
        let cand = format!("{esc}_{i}");
        if !used.contains(&cand) {
            used.insert(cand.clone());
            return cand;
        }
        i += 1;
    }
}

fn tuple_variant_field_names(field_count: usize) -> Vec<String> {
    match field_count {
        0 => Vec::new(),
        1 => vec!["payload".to_string()],
        n => (0..n).map(|i| format!("variant_field_{i}")).collect(),
    }
}

#[derive(Debug, Clone)]
struct TypeMirror {
    beskind_ty: String,
    stub_note: Option<String>,
}

fn parse_top_level_item(
    item: &Item,
    record_skips: bool,
    skipped_generics: &mut Vec<String>,
    source_rel_path: &str,
) -> Option<(String, ParsedType)> {
    let stub = reflect_stub_path();
    match item {
        Item::Struct(s) if matches!(s.vis, Visibility::Public(_)) => {
            if !s.generics.params.is_empty() {
                if record_skips {
                    skipped_generics.push(s.ident.to_string());
                }
                return None;
            }
            let rust_doc_summary = doc_summary_from_attrs(&s.attrs);
            let fields = struct_fields(&s.fields, &stub);
            Some((
                s.ident.to_string(),
                ParsedType {
                    kind: TypeKind::Struct,
                    source_rel_path: source_rel_path.to_string(),
                    rust_doc_summary,
                    fields,
                    variants: Vec::new(),
                },
            ))
        }
        Item::Enum(e) if matches!(e.vis, Visibility::Public(_)) => {
            if !e.generics.params.is_empty() {
                if record_skips {
                    skipped_generics.push(e.ident.to_string());
                }
                return None;
            }
            let rust_doc_summary = doc_summary_from_attrs(&e.attrs);
            let variants = e
                .variants
                .iter()
                .map(|v| parse_enum_variant(v, &stub))
                .collect();
            Some((
                e.ident.to_string(),
                ParsedType {
                    kind: TypeKind::Enum,
                    source_rel_path: source_rel_path.to_string(),
                    rust_doc_summary,
                    fields: Vec::new(),
                    variants,
                },
            ))
        }
        _ => None,
    }
}

fn parse_enum_variant(v: &syn::Variant, stub: &str) -> EnumVariantMirror {
    let rust_doc_summary = doc_summary_from_attrs(&v.attrs);
    let shape = match &v.fields {
        Fields::Unit => VariantShape::Unit,
        Fields::Unnamed(uf) => {
            let fields: Vec<_> = uf
                .unnamed
                .iter()
                .filter(|f| !field_has_ast_skip(&f.attrs))
                .collect();
            let count = fields.len();
            let names = tuple_variant_field_names(count);
            let mut used = BTreeSet::new();
            let mut out = Vec::new();
            for (f, base_name) in fields.into_iter().zip(names) {
                let tm = map_rust_type(&f.ty, stub);
                let name = unique_field_name(&base_name, &mut used);
                out.push(FieldMirror {
                    name,
                    beskind_ty: tm.beskind_ty,
                    stub_note: tm.stub_note,
                });
            }
            VariantShape::Tuple(out)
        }
        Fields::Named(nf) => {
            let mut used = BTreeSet::new();
            let mut out = Vec::new();
            for f in &nf.named {
                if field_has_ast_skip(&f.attrs) {
                    continue;
                }
                let base = f
                    .ident
                    .as_ref()
                    .map(|i| i.to_string())
                    .unwrap_or_else(|| "field".into());
                let tm = map_rust_type(&f.ty, stub);
                let name = unique_field_name(&base, &mut used);
                out.push(FieldMirror {
                    name,
                    beskind_ty: tm.beskind_ty,
                    stub_note: tm.stub_note,
                });
            }
            VariantShape::Struct(out)
        }
    };
    EnumVariantMirror {
        name: v.ident.to_string(),
        rust_doc_summary,
        shape,
    }
}

fn struct_fields(fields: &Fields, stub: &str) -> Vec<FieldMirror> {
    match fields {
        Fields::Named(named) => {
            let mut used = BTreeSet::new();
            named
                .named
                .iter()
                .filter(|f| !field_has_ast_skip(&f.attrs))
                .map(|f| {
                    let base = f.ident.as_ref().expect("named field").to_string();
                    let tm = map_rust_type(&f.ty, stub);
                    let name = unique_field_name(&base, &mut used);
                    FieldMirror {
                        name,
                        beskind_ty: tm.beskind_ty,
                        stub_note: tm.stub_note,
                    }
                })
                .collect()
        }
        Fields::Unnamed(unnamed) => {
            let fields: Vec<_> = unnamed
                .unnamed
                .iter()
                .filter(|f| !field_has_ast_skip(&f.attrs))
                .collect();
            let mut used = BTreeSet::new();
            fields
                .into_iter()
                .enumerate()
                .map(|(i, f)| {
                    let base = format!("field_{i}");
                    let tm = map_rust_type(&f.ty, stub);
                    let name = unique_field_name(&base, &mut used);
                    FieldMirror {
                        name,
                        beskind_ty: tm.beskind_ty,
                        stub_note: tm.stub_note,
                    }
                })
                .collect()
        }
        Fields::Unit => Vec::new(),
    }
}

fn field_has_ast_skip(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("ast") {
            return false;
        }
        match &a.meta {
            Meta::List(list) => list.tokens.to_string().contains("skip"),
            _ => false,
        }
    })
}

fn map_rust_type(ty: &Type, stub_path: &str) -> TypeMirror {
    match ty {
        Type::Path(tp) => map_path_type(tp, stub_path),
        Type::Reference(r) => map_rust_type(&r.elem, stub_path),
        Type::Paren(p) => map_rust_type(&p.elem, stub_path),
        Type::Tuple(t) if t.elems.is_empty() => TypeMirror {
            beskind_ty: "()".into(),
            stub_note: Some("Rust unit type `()` has no Mod SDK mapping".into()),
        },
        Type::Tuple(_) => TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some("Rust tuple type is not expanded in Mod SDK".into()),
        },
        Type::Slice(_) | Type::Array(_) => TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some("Rust slice/array type is not mapped field-for-field".into()),
        },
        _ => TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some("Rust type shape not represented in generated Mod SDK nodes".into()),
        },
    }
}

fn map_path_type(tp: &syn::TypePath, stub_path: &str) -> TypeMirror {
    let path = &tp.path;
    let Some(seg) = path.segments.last() else {
        return TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some("empty Rust path".into()),
        };
    };
    let ident = seg.ident.to_string();
    let args = &seg.arguments;

    if let ("Option", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            if is_primitive_option_inner(inner) {
                return map_rust_type(inner, stub_path);
            }
        }
        return TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some(
                "Option with non-primitive inner type is collapsed to ReflectStub in Mod SDK"
                    .into(),
            ),
        };
    }
    if let ("Vec", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            if matches!(inner, Type::Path(p) if p.path.is_ident("u8")) {
                return TypeMirror {
                    beskind_ty: "string".into(),
                    stub_note: None,
                };
            }
        }
        return TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some(
                "Vec subtrees are not expanded field-for-field in Mod SDK (ReflectStub)"
                    .into(),
            ),
        };
    }
    if let ("Box", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            return map_rust_type(inner, stub_path);
        }
        return TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some("Box without inner type".into()),
        };
    }
    if let ("Spanned", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            return map_rust_type(inner, stub_path);
        }
        return TypeMirror {
            beskind_ty: stub_path.into(),
            stub_note: Some("Spanned without inner type".into()),
        };
    }

    match ident.as_str() {
        "bool" => TypeMirror {
            beskind_ty: "bool".into(),
            stub_note: None,
        },
        "char" => TypeMirror {
            beskind_ty: "string".into(),
            stub_note: None,
        },
        "String" => TypeMirror {
            beskind_ty: "string".into(),
            stub_note: None,
        },
        "usize" | "isize" | "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => {
            TypeMirror {
                beskind_ty: "i64".into(),
                stub_note: None,
            }
        }
        "f32" | "f64" => TypeMirror {
            beskind_ty: "f64".into(),
            stub_note: None,
        },
        _ => {
            let fq = path
                .segments
                .iter()
                .map(|s| s.ident.to_string())
                .collect::<Vec<_>>()
                .join("::");
            if fq.contains("LeadingDocComment") || fq.contains("SpanInfo") {
                return TypeMirror {
                    beskind_ty: stub_path.into(),
                    stub_note: Some(
                        "LeadingDocComment / SpanInfo are host-only and not modeled as syntax nodes"
                            .into(),
                    ),
                };
            }
            TypeMirror {
                beskind_ty: format!("{}.{}", SYNTAX_NODES_MODULE_PREFIX, ident),
                stub_note: None,
            }
        }
    }
}

fn is_primitive_option_inner(ty: &Type) -> bool {
    match ty {
        Type::Path(tp) => {
            tp.path.is_ident("bool")
                || tp.path.is_ident("char")
                || tp.path.is_ident("String")
                || matches!(
                    tp.path.get_ident().map(|i| i.to_string()).as_deref(),
                    Some(
                        "usize"
                            | "isize"
                            | "u8"
                            | "u16"
                            | "u32"
                            | "u64"
                            | "i8"
                            | "i16"
                            | "i32"
                            | "i64"
                            | "f32"
                            | "f64"
                    )
                )
        }
        _ => false,
    }
}

/// Write `Syntax/Nodes/*.bd`, `Syntax/Nodes.bd` barrel, `_inventory.txt`, and thin `Syntax.bd`.
pub fn emit_syntax_sdk(
    compiler_sdk_compiler_dir: &Path,
    analysis_src: &Path,
) -> Result<SyntaxNodesGenReport, std::io::Error> {
    let (decls, skipped_generics) = collect_declarations(analysis_src)?;

    let syntax_dir = compiler_sdk_compiler_dir.join("Syntax");
    let nodes_dir = syntax_dir.join("Nodes");
    fs::create_dir_all(&nodes_dir)?;

    let type_names: Vec<String> = decls.keys().cloned().collect();

    for (name, parsed) in &decls {
        let body = emit_type_bd(name, parsed);
        let mut out = String::new();
        out.push_str(BANNER);
        out.push('\n');
        out.push_str(&body);
        out.push('\n');
        let path = nodes_dir.join(format!("{name}.bd"));
        fs::write(path, out)?;
    }

    // `_inventory.txt` — one logical type name per line (sorted via BTreeMap iteration).
    let inv_path = nodes_dir.join("_inventory.txt");
    let inv_body = type_names.join("\n") + "\n";
    fs::write(inv_path, &inv_body)?;

    // Barrel: `Syntax/Nodes.bd`
    let mut barrel = String::new();
    barrel.push_str(BANNER);
    barrel.push('\n');
    for name in &type_names {
        barrel.push_str(&format!(
            "pub mod {}.{};\n",
            SYNTAX_NODES_MODULE_PREFIX, name
        ));
    }
    fs::write(syntax_dir.join("Nodes.bd"), barrel)?;

    // Thin `Syntax.bd`
    let syntax_bd = format!(
        r#"// CHECKED IN: regenerated by packages/compiler-sdk/regen_mod_sdk_surfaces.sh
// Rust sources in beskid_analysis are authoritative; nested shapes live under Syntax/Nodes/.

pub type ReflectStub {{}}

pub mod Beskid.Compiler.Syntax.Nodes;

// Hand-maintained facade ------------------------------------------------------
// Immutable syntax node views for capture keys and typed emit construction (Mod SDK).
// Host supplies concrete trees; this package carries stable layout/version metadata only.

// Facade contract version aligned with platform-spec Beskid.Compiler.Syntax hub.
pub string SyntaxFacadeVersion() {{
    return "0.2.0";
}}
"#
    );
    fs::write(compiler_sdk_compiler_dir.join("Syntax.bd"), syntax_bd)?;

    Ok(SyntaxNodesGenReport {
        type_names,
        skipped_generics,
        skipped_opaque_paths: Vec::new(),
    })
}

fn emit_reflect_stub_doc_lines(type_name: &str, parsed: &ParsedType, stub: &str) -> Vec<String> {
    let mut out = Vec::new();
    match parsed.kind {
        TypeKind::Struct => {
            for f in &parsed.fields {
                if f.beskind_ty == stub {
                    let why = f
                        .stub_note
                        .as_deref()
                        .unwrap_or("Mod SDK placeholder (no per-field expansion).");
                    out.push(format!(
                        "/// - Struct field `{fname}`: ReflectStub — {why}",
                        fname = f.name
                    ));
                }
            }
        }
        TypeKind::Enum => {
            for v in &parsed.variants {
                let fields: &[FieldMirror] = match &v.shape {
                    VariantShape::Unit => &[],
                    VariantShape::Tuple(fs) | VariantShape::Struct(fs) => fs.as_slice(),
                };
                for f in fields {
                    if f.beskind_ty == stub {
                        let why = f
                            .stub_note
                            .as_deref()
                            .unwrap_or("Mod SDK placeholder (no per-field expansion).");
                        out.push(format!(
                            "/// - Variant `{type_name}::{vname}` field `{fname}`: ReflectStub — {why}",
                            vname = v.name,
                            fname = f.name
                        ));
                    }
                }
            }
        }
    }
    out
}

fn emit_type_doc_block(type_name: &str, parsed: &ParsedType) -> String {
    let stub = reflect_stub_path();
    let rust_loc = format!("crates/beskid_analysis/src/{}", parsed.source_rel_path);
    let mut lines = vec![format!(
        "/// Generated syntax node mirror: `{rust_loc}` — `{type_name}`."
    )];
    if let Some(d) = &parsed.rust_doc_summary {
        lines.push(format!("/// Rust docs: {d}"));
    }
    let stub_lines = emit_reflect_stub_doc_lines(type_name, parsed, stub);
    if !stub_lines.is_empty() {
        lines.push("///".into());
        lines.push("/// ReflectStub fields (not expanded in this shape):".into());
        lines.extend(stub_lines);
    }
    lines.join("\n") + "\n"
}

fn format_variant_line(v: &EnumVariantMirror) -> String {
    match &v.shape {
        VariantShape::Unit => format!("    {},", v.name),
        VariantShape::Tuple(fields) | VariantShape::Struct(fields) => {
            if fields.is_empty() {
                format!("    {},", v.name)
            } else {
                let inner = fields
                    .iter()
                    .map(|f| format!("{} {}", f.beskind_ty, f.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("    {}({inner}),", v.name)
            }
        }
    }
}

fn emit_type_bd(name: &str, parsed: &ParsedType) -> String {
    let doc = emit_type_doc_block(name, parsed);
    let decl = match parsed.kind {
        TypeKind::Struct => {
            let body = if parsed.fields.is_empty() {
                format!("pub type {name} {{\n}}")
            } else {
                let lines: Vec<String> = parsed
                    .fields
                    .iter()
                    .map(|f| format!("    {} {},", f.beskind_ty, f.name))
                    .collect();
                format!("pub type {name} {{\n{}\n}}", lines.join("\n"))
            };
            body
        }
        TypeKind::Enum => {
            let lines: Vec<String> = parsed.variants.iter().map(format_variant_line).collect();
            format!("pub enum {name}\n{{\n{}\n}}", lines.join("\n"))
        }
    };
    doc + &decl
}

/// Parse `ReflectSdkNodeKind` variant names from `compiler_sdk_reflect.rs` (set equality tests).
pub fn reflect_sdk_node_kind_names(reflect_rs: &Path) -> Result<BTreeSet<String>, std::io::Error> {
    let text = fs::read_to_string(reflect_rs)?;
    let mut out = BTreeSet::new();
    let mut in_enum = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with("pub enum ReflectSdkNodeKind") {
            in_enum = true;
            continue;
        }
        if in_enum {
            if t.starts_with('}') && !t.starts_with("},") {
                break;
            }
            if let Some(name) = t.strip_suffix(',') {
                let name = name.trim();
                if name.is_empty() || name.starts_with("//") {
                    continue;
                }
                if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
                    out.insert(name.to_string());
                }
            }
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn trim_field_token(tok: &str) -> &str {
        tok.trim_end_matches(|c: char| c == ',' || c == ')' || c == ';')
    }

    /// True for legacy `f0`/`f1` positional placeholders (not `f32`/`f64` types).
    fn is_fnumeric_placeholder_field(tok: &str) -> bool {
        let w = trim_field_token(tok);
        if w == "f32" || w == "f64" {
            return false;
        }
        let Some(rest) = w.strip_prefix('f') else {
            return false;
        };
        !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit())
    }

    #[test]
    fn inventory_matches_reflect_sdk_node_kinds() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let reflect_rs = manifest.join("../beskid_analysis/src/compiler_sdk_reflect.rs");
        let inv: BTreeSet<String> = inventory_syntax_type_names(&analysis_src)
            .expect("inventory")
            .into_iter()
            .collect();
        let kinds = reflect_sdk_node_kind_names(&reflect_rs).expect("reflect parse");
        assert!(
            kinds.is_subset(&inv),
            "every ReflectSdkNodeKind must have a generated node file; missing: {:?}",
            kinds.difference(&inv).collect::<Vec<_>>()
        );
        // `AssignOp` is nested under `AssignExpression` (no standalone `NodeKind` today).
        let allowed_extra: BTreeSet<String> = ["AssignOp", "FieldKind"]
            .iter()
            .map(|s| (*s).to_string())
            .collect();
        let extras: BTreeSet<_> = inv.difference(&kinds).cloned().collect();
        assert!(
            extras.is_subset(&allowed_extra),
            "unexpected syntax types not listed in ReflectSdkNodeKind: {:?}",
            extras.difference(&allowed_extra).collect::<Vec<_>>()
        );
    }

    #[test]
    fn golden_syntax_nodes_inventory_matches_scan() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let names = inventory_syntax_type_names(&analysis_src).expect("inventory");
        let got = names.join("\n") + "\n";
        let expected = include_str!("../tests/expected/syntax_nodes_inventory.txt");
        assert_eq!(
            got, expected,
            "update tests/expected/syntax_nodes_inventory.txt after adding/removing syntax surface types"
        );
    }

    /// Generated `Syntax/Nodes/*.bd` must not use legacy `f0`/`f1` positional field names.
    #[test]
    fn syntax_node_emission_avoids_fnumeric_field_names() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let (decls, _) = collect_declarations(&analysis_src).expect("collect");
        for (name, parsed) in &decls {
            let text = emit_type_bd(name, parsed);
            for line in text.lines() {
                let trimmed = line.trim_start();
                if trimmed.starts_with("///") {
                    continue;
                }
                for tok in line.split_whitespace() {
                    assert!(
                        !is_fnumeric_placeholder_field(tok),
                        "legacy fN field placeholder in emitted `{name}`: {line}"
                    );
                }
            }
        }
    }
}
