//! Per-type Beskid (`.bd`) emission for the syntax AST vocabulary in `beskid_analysis`.
//!
//! Scans `syntax/{items,types,expressions,statements,common}/**/*.rs`, emits one file per
//! `pub struct` / `pub enum` (skipping `mod.rs` and helpers). Rust generic parameters map to
//! `ReflectStub` in generated fields; leading docs emit matching `@par` lines.
//!
//! Leading `///` bodies use the structured doc subset from `beskid_analysis` / `beskid_doc.pest`
//! (`@variant`, `@par`, and plain `Run` text). Mirrored field `///` lines are taken from Rust
//! `#[doc = ...]` only; `@arg` / `@returns` stay for hand-authored callables.

use std::collections::{BTreeMap, BTreeSet};
use std::ffi::OsStr;
use std::fs;
use std::path::Path;

use syn::{
    Attribute, Expr, Fields, GenericArgument, GenericParam, Generics, Item, Lit, Meta,
    PathArguments, Type, Visibility,
};

use crate::emit_idents::rust_snake_to_beskid_field_camel;
use crate::syntax_helpers::{
    self, HelperPaths, list_element_rust_name, option_payload_rust_name, peel_type,
    vec_element_type,
};

pub use crate::syntax_helpers::{
    SYNTAX_NODES_MODULE_PREFIX, SYNTAX_SCAN_SKIP_FILES, SYNTAX_SCAN_SUBDIRS, reflect_stub_path,
};

pub(crate) const BANNER: &str =
    "// Generated by beskid_ast_reflect_gen (syntax nodes). Do not hand-edit.\n";

#[derive(Debug, Clone)]
pub struct SyntaxNodesGenReport {
    pub type_names: Vec<String>,
    pub skipped_generics: Vec<String>,
    pub skipped_opaque_paths: Vec<String>,
}

/// Discover all `pub struct` / `pub enum` names under the syntax scan dirs.
pub fn inventory_syntax_type_names(analysis_src: &Path) -> Result<Vec<String>, std::io::Error> {
    let (decls, _) = collect_declarations(analysis_src, None)?;
    Ok(decls
        .keys()
        .filter(|k| !crate::syntax_traversal::is_host_only_type(k))
        .cloned()
        .collect())
}

fn collect_declarations(
    analysis_src: &Path,
    helpers: Option<&HelperPaths>,
) -> Result<(BTreeMap<String, ParsedType>, Vec<String>), std::io::Error> {
    let files = syntax_helpers::load_syntax_files(analysis_src)?;
    let mut map = BTreeMap::new();
    let skipped_generics = Vec::new();
    for (rel_path, file) in &files {
        for item in &file.items {
            if let Some((ident, parsed)) = parse_top_level_item(item, rel_path.as_str(), helpers) {
                map.insert(ident, parsed);
            }
        }
    }
    Ok((map, skipped_generics))
}

#[derive(Debug, Clone)]
pub struct ParsedType {
    pub kind: TypeKind,
    /// Relative path under `crates/beskid_analysis/src`, e.g. `syntax/expressions/pattern.rs`.
    pub source_rel_path: String,
    /// Rust `///` lines on the type (trimmed), in source order.
    pub rust_doc_lines: Vec<String>,
    /// Rust generic type parameter names (sorted) for `@par` emission; empty when non-generic.
    pub type_param_names: Vec<String>,
    pub fields: Vec<FieldMirror>,
    pub variants: Vec<EnumVariantMirror>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypeKind {
    Struct,
    Enum,
}

#[derive(Debug, Clone)]
pub struct FieldMirror {
    /// Beskid field / parameter name (camelCase where applicable).
    pub name: String,
    /// Rust-side identifier or slot label (e.g. `return_type`, `` `payload` `` tuple slot).
    pub rust_field_source: String,
    /// Beskid type written in generated `.bd` (qualified path, primitive, or `ReflectStub`).
    pub beskid_ty: String,
    /// When `beskid_ty` is `ReflectStub`, human-readable reason for Mod SDK consumers.
    pub stub_note: Option<String>,
    /// Rust `///` lines from the mirrored field when present. `ReflectStub` payloads get one trailing Mod SDK note.
    pub rust_doc_lines: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct EnumVariantMirror {
    pub name: String,
    /// Rust `///` lines on the variant plus a trailing `@variant(…)` shape summary (`beskid_doc.pest`).
    pub rust_doc_lines: Vec<String>,
    pub shape: VariantShape,
}

#[derive(Debug, Clone)]
pub enum VariantShape {
    Unit,
    Tuple(Vec<FieldMirror>),
    /// Named fields inside the variant (rare in scanned syntax enums).
    Struct(Vec<FieldMirror>),
}

/// Every `#[doc = "..."]` line (syn expands `///` into these), preserving inner newlines.
fn doc_lines_from_attrs(attrs: &[Attribute]) -> Vec<String> {
    let mut out = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        let Meta::NameValue(nv) = &attr.meta else {
            continue;
        };
        let Expr::Lit(syn::ExprLit {
            lit: Lit::Str(s), ..
        }) = &nv.value
        else {
            continue;
        };
        for raw in s.value().lines() {
            let t = raw.trim_end();
            if t.is_empty() {
                continue;
            }
            out.push(t.trim_start().to_string());
        }
    }
    out
}

/// Suffix text for [`doc_variant_line`]: one line, no `@`, no raw newlines
/// (see `beskid_analysis/src/beskid_doc.pest` `ArgSuffix` / `VariantSuffix`).
fn sanitize_doc_directive_suffix(s: &str) -> String {
    s.trim()
        .chars()
        .map(|c| match c {
            '\n' | '\r' => ' ',
            '@' => ' ',
            _ => c,
        })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

/// `@variant(name) description` — `beskid_doc.pest` `VariantTag`.
fn doc_variant_line(ident: &str, description: &str) -> String {
    format!(
        "@variant({}) {}",
        ident,
        sanitize_doc_directive_suffix(description)
    )
}

/// `@par(name) description` — `beskid_doc.pest` `ParTag`.
fn doc_par_line(ident: &str, description: &str) -> String {
    format!(
        "@par({}) {}",
        ident,
        sanitize_doc_directive_suffix(description)
    )
}

fn type_param_names_sorted(generics: &Generics) -> (BTreeSet<String>, Vec<String>) {
    let set: BTreeSet<String> = generics
        .params
        .iter()
        .filter_map(|p| match p {
            GenericParam::Type(t) => Some(t.ident.to_string()),
            _ => None,
        })
        .collect();
    let names = set.iter().cloned().collect::<Vec<_>>();
    (set, names)
}

fn field_sdk_doc_lines(
    attrs: &[Attribute],
    beskid_ty: &str,
    stub_note: Option<&str>,
) -> Vec<String> {
    let mut lines = doc_lines_from_attrs(attrs);
    let stub = reflect_stub_path();
    if beskid_ty == stub {
        let note = stub_note.unwrap_or("opaque or unmapped Rust type in this surface");
        lines.push(sanitize_doc_directive_suffix(&format!(
            "ReflectStub in Mod SDK ({note})."
        )));
    }
    lines
}

fn variant_sdk_summary_line(name: &str, shape: &VariantShape) -> String {
    let suffix = match shape {
        VariantShape::Unit => "unit variant (no payload).".into(),
        VariantShape::Tuple(fs) if fs.is_empty() => "empty tuple payload.".into(),
        VariantShape::Tuple(fs) => {
            let ps: Vec<String> = fs
                .iter()
                .map(|f| format!("{} ({})", f.name, f.beskid_ty))
                .collect();
            format!("tuple payload: {}.", ps.join(", "))
        }
        VariantShape::Struct(fs) => {
            let ps: Vec<String> = fs
                .iter()
                .map(|f| format!("{}: {}", f.name, f.beskid_ty))
                .collect();
            format!("struct payload: {}.", ps.join(", "))
        }
    };
    doc_variant_line(name, &suffix)
}

fn variant_index_suffix(shape: &VariantShape) -> String {
    match shape {
        VariantShape::Unit => "unit (no payload)".into(),
        VariantShape::Tuple(fs) if fs.is_empty() => "empty tuple".into(),
        VariantShape::Tuple(fs) => {
            let inner = fs
                .iter()
                .map(|f| format!("{}: {}", f.name, f.beskid_ty))
                .collect::<Vec<_>>()
                .join(", ");
            format!("tuple ({inner})")
        }
        VariantShape::Struct(fs) => {
            let inner = fs
                .iter()
                .map(|f| format!("{}: {}", f.name, f.beskid_ty))
                .collect::<Vec<_>>()
                .join(", ");
            format!("struct {{ {inner} }}")
        }
    }
}

fn unique_field_name(base: &str, used: &mut BTreeSet<String>) -> String {
    let esc = rust_snake_to_beskid_field_camel(base);
    if !used.contains(&esc) {
        used.insert(esc.clone());
        return esc;
    }
    let mut i = 2u32;
    loop {
        let cand = format!("{esc}{i}");
        if !used.contains(&cand) {
            used.insert(cand.clone());
            return cand;
        }
        i += 1;
    }
}

fn tuple_variant_field_names(field_count: usize) -> Vec<String> {
    match field_count {
        0 => Vec::new(),
        1 => vec!["payload".to_string()],
        n => (0..n).map(|i| format!("variant_field_{i}")).collect(),
    }
}

#[derive(Debug, Clone)]
struct TypeMirror {
    /// Target Beskid type string for this Rust type.
    beskid_ty: String,
    stub_note: Option<String>,
}

fn parse_top_level_item(
    item: &Item,
    source_rel_path: &str,
    helpers: Option<&HelperPaths>,
) -> Option<(String, ParsedType)> {
    let stub = reflect_stub_path();
    match item {
        Item::Struct(s) if matches!(s.vis, Visibility::Public(_)) => {
            let (type_param_set, type_param_names) = type_param_names_sorted(&s.generics);
            let rust_doc_lines = doc_lines_from_attrs(&s.attrs);
            let fields = struct_fields(&s.fields, stub, helpers, &type_param_set);
            Some((
                s.ident.to_string(),
                ParsedType {
                    kind: TypeKind::Struct,
                    source_rel_path: source_rel_path.to_string(),
                    rust_doc_lines,
                    type_param_names,
                    fields,
                    variants: Vec::new(),
                },
            ))
        }
        Item::Enum(e) if matches!(e.vis, Visibility::Public(_)) => {
            let (type_param_set, type_param_names) = type_param_names_sorted(&e.generics);
            let rust_doc_lines = doc_lines_from_attrs(&e.attrs);
            let variants = e
                .variants
                .iter()
                .map(|v| parse_enum_variant(v, stub, helpers, &type_param_set))
                .collect();
            Some((
                e.ident.to_string(),
                ParsedType {
                    kind: TypeKind::Enum,
                    source_rel_path: source_rel_path.to_string(),
                    rust_doc_lines,
                    type_param_names,
                    fields: Vec::new(),
                    variants,
                },
            ))
        }
        _ => None,
    }
}

fn parse_enum_variant(
    v: &syn::Variant,
    stub: &str,
    helpers: Option<&HelperPaths>,
    type_params: &BTreeSet<String>,
) -> EnumVariantMirror {
    let name = v.ident.to_string();
    let shape = match &v.fields {
        Fields::Unit => VariantShape::Unit,
        Fields::Unnamed(uf) => {
            let fields: Vec<_> = uf
                .unnamed
                .iter()
                .filter(|f| !field_has_ast_skip(&f.attrs))
                .collect();
            let count = fields.len();
            let names = tuple_variant_field_names(count);
            let mut used = BTreeSet::new();
            let mut out = Vec::new();
            for (f, base_name) in fields.into_iter().zip(names) {
                let tm = map_rust_type(&f.ty, stub, helpers, type_params);
                let beskid_name = unique_field_name(&base_name, &mut used);
                let rust_src = format!("{name}::{base_name}");
                let rust_doc_lines =
                    field_sdk_doc_lines(&f.attrs, &tm.beskid_ty, tm.stub_note.as_deref());
                out.push(FieldMirror {
                    name: beskid_name,
                    rust_field_source: rust_src,
                    beskid_ty: tm.beskid_ty,
                    stub_note: tm.stub_note,
                    rust_doc_lines,
                });
            }
            VariantShape::Tuple(out)
        }
        Fields::Named(nf) => {
            let mut used = BTreeSet::new();
            let mut out = Vec::new();
            for f in &nf.named {
                if field_has_ast_skip(&f.attrs) {
                    continue;
                }
                let base = f
                    .ident
                    .as_ref()
                    .map(|i| i.to_string())
                    .unwrap_or_else(|| "field".into());
                let tm = map_rust_type(&f.ty, stub, helpers, type_params);
                let beskid_name = unique_field_name(&base, &mut used);
                let rust_src = format!("{name}::{base}");
                let rust_doc_lines =
                    field_sdk_doc_lines(&f.attrs, &tm.beskid_ty, tm.stub_note.as_deref());
                out.push(FieldMirror {
                    name: beskid_name,
                    rust_field_source: rust_src,
                    beskid_ty: tm.beskid_ty,
                    stub_note: tm.stub_note,
                    rust_doc_lines,
                });
            }
            VariantShape::Struct(out)
        }
    };
    let mut rust_doc_lines = doc_lines_from_attrs(&v.attrs);
    rust_doc_lines.push(variant_sdk_summary_line(&name, &shape));
    EnumVariantMirror {
        name,
        rust_doc_lines,
        shape,
    }
}

fn struct_fields(
    fields: &Fields,
    stub: &str,
    helpers: Option<&HelperPaths>,
    type_params: &BTreeSet<String>,
) -> Vec<FieldMirror> {
    match fields {
        Fields::Named(named) => {
            let mut used = BTreeSet::new();
            named
                .named
                .iter()
                .filter(|f| !field_has_ast_skip(&f.attrs))
                .map(|f| {
                    let base = f.ident.as_ref().expect("named field").to_string();
                    let tm = map_rust_type(&f.ty, stub, helpers, type_params);
                    let name = unique_field_name(&base, &mut used);
                    let rust_doc_lines =
                        field_sdk_doc_lines(&f.attrs, &tm.beskid_ty, tm.stub_note.as_deref());
                    FieldMirror {
                        name,
                        rust_field_source: base,
                        beskid_ty: tm.beskid_ty,
                        stub_note: tm.stub_note,
                        rust_doc_lines,
                    }
                })
                .collect()
        }
        Fields::Unnamed(unnamed) => {
            let fields: Vec<_> = unnamed
                .unnamed
                .iter()
                .filter(|f| !field_has_ast_skip(&f.attrs))
                .collect();
            let mut used = BTreeSet::new();
            fields
                .into_iter()
                .enumerate()
                .map(|(i, f)| {
                    let base = format!("field_{i}");
                    let tm = map_rust_type(&f.ty, stub, helpers, type_params);
                    let name = unique_field_name(&base, &mut used);
                    let rust_src = format!("tuple field {i} (`{base}`)");
                    let rust_doc_lines =
                        field_sdk_doc_lines(&f.attrs, &tm.beskid_ty, tm.stub_note.as_deref());
                    FieldMirror {
                        name,
                        rust_field_source: rust_src,
                        beskid_ty: tm.beskid_ty,
                        stub_note: tm.stub_note,
                        rust_doc_lines,
                    }
                })
                .collect()
        }
        Fields::Unit => Vec::new(),
    }
}

fn field_has_ast_skip(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("ast") {
            return false;
        }
        match &a.meta {
            Meta::List(list) => list.tokens.to_string().contains("skip"),
            _ => false,
        }
    })
}

fn map_rust_type(
    ty: &Type,
    stub_path: &str,
    helpers: Option<&HelperPaths>,
    type_params: &BTreeSet<String>,
) -> TypeMirror {
    match ty {
        Type::Path(tp) => map_path_type(tp, stub_path, helpers, type_params),
        Type::Reference(r) => map_rust_type(&r.elem, stub_path, helpers, type_params),
        Type::Paren(p) => map_rust_type(&p.elem, stub_path, helpers, type_params),
        Type::Tuple(t) if t.elems.is_empty() => TypeMirror {
            beskid_ty: "()".into(),
            stub_note: Some("Rust unit type `()` has no Mod SDK mapping".into()),
        },
        Type::Tuple(_) => TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some("Rust tuple type is not expanded in Mod SDK".into()),
        },
        Type::Slice(_) | Type::Array(_) => TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some("Rust slice/array type is not mapped field-for-field".into()),
        },
        _ => TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some("Rust type shape not represented in generated Mod SDK nodes".into()),
        },
    }
}

fn map_path_type(
    tp: &syn::TypePath,
    stub_path: &str,
    helpers: Option<&HelperPaths>,
    type_params: &BTreeSet<String>,
) -> TypeMirror {
    let path = &tp.path;
    let Some(seg) = path.segments.last() else {
        return TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some("empty Rust path".into()),
        };
    };
    let ident = seg.ident.to_string();
    let args = &seg.arguments;

    if type_params.contains(&ident) && matches!(args, PathArguments::None) {
        return TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some(format!(
                "Rust generic type parameter `{ident}` (mirrored as ReflectStub in Mod SDK)"
            )),
        };
    }

    if let ("Option", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            let p = peel_type(inner);
            if is_primitive_option_inner(p) {
                return map_rust_type(p, stub_path, helpers, type_params);
            }
            if let Some(h) = helpers {
                if let Some(vel) = vec_element_type(p) {
                    let vp = peel_type(vel);
                    if matches!(vp, Type::Path(pp) if pp.path.is_ident("u8")) {
                        return TypeMirror {
                            beskid_ty: "string".into(),
                            stub_note: None,
                        };
                    }
                    if let Some(el) = list_element_rust_name(vel)
                        && let Some(list_path) = h.list_by_element.get(&el)
                    {
                        let list_base = list_path.rsplit('.').next().unwrap();
                        if let Some(opt_path) = h.optional_by_inner.get(list_base) {
                            return TypeMirror {
                                beskid_ty: opt_path.clone(),
                                stub_note: None,
                            };
                        }
                    }
                }
                if let Some(nm) = option_payload_rust_name(p)
                    && let Some(opt_path) = h.optional_by_inner.get(&nm)
                {
                    return TypeMirror {
                        beskid_ty: opt_path.clone(),
                        stub_note: None,
                    };
                }
            }
        }
        return TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some(
                "Option with non-primitive inner type is collapsed to ReflectStub in Mod SDK"
                    .into(),
            ),
        };
    }
    if let ("Vec", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            let pi = peel_type(inner);
            if matches!(pi, Type::Path(p) if p.path.is_ident("u8")) {
                return TypeMirror {
                    beskid_ty: "string".into(),
                    stub_note: None,
                };
            }
            if let Some(h) = helpers
                && let Some(el) = list_element_rust_name(pi)
                && let Some(p) = h.list_by_element.get(&el)
            {
                return TypeMirror {
                    beskid_ty: p.clone(),
                    stub_note: None,
                };
            }
        }
        return TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some(
                "Vec subtrees are not expanded field-for-field in Mod SDK (ReflectStub)".into(),
            ),
        };
    }
    if let ("Box", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            return map_rust_type(inner, stub_path, helpers, type_params);
        }
        return TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some("Box without inner type".into()),
        };
    }
    if let ("Spanned", PathArguments::AngleBracketed(ab)) = (ident.as_str(), args) {
        if let Some(GenericArgument::Type(inner)) = ab.args.first() {
            return map_rust_type(inner, stub_path, helpers, type_params);
        }
        return TypeMirror {
            beskid_ty: stub_path.into(),
            stub_note: Some("Spanned without inner type".into()),
        };
    }

    match ident.as_str() {
        "bool" => TypeMirror {
            beskid_ty: "bool".into(),
            stub_note: None,
        },
        "char" => TypeMirror {
            beskid_ty: "string".into(),
            stub_note: None,
        },
        "String" => TypeMirror {
            beskid_ty: "string".into(),
            stub_note: None,
        },
        "usize" | "isize" | "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => {
            TypeMirror {
                beskid_ty: "i64".into(),
                stub_note: None,
            }
        }
        "f32" | "f64" => TypeMirror {
            beskid_ty: "f64".into(),
            stub_note: None,
        },
        _ => {
            let fq = path
                .segments
                .iter()
                .map(|s| s.ident.to_string())
                .collect::<Vec<_>>()
                .join("::");
            if fq.contains("LeadingDocComment") || fq.contains("SpanInfo") {
                return TypeMirror {
                    beskid_ty: stub_path.into(),
                    stub_note: Some(
                        "LeadingDocComment / SpanInfo are host-only and not modeled as syntax nodes"
                            .into(),
                    ),
                };
            }
            TypeMirror {
                beskid_ty: format!("{}.{}", SYNTAX_NODES_MODULE_PREFIX, ident),
                stub_note: None,
            }
        }
    }
}

fn is_primitive_option_inner(ty: &Type) -> bool {
    match ty {
        Type::Path(tp) => {
            tp.path.is_ident("bool")
                || tp.path.is_ident("char")
                || tp.path.is_ident("String")
                || matches!(
                    tp.path.get_ident().map(|i| i.to_string()).as_deref(),
                    Some(
                        "usize"
                            | "isize"
                            | "u8"
                            | "u16"
                            | "u32"
                            | "u64"
                            | "i8"
                            | "i16"
                            | "i32"
                            | "i64"
                            | "f32"
                            | "f64"
                    )
                )
        }
        _ => false,
    }
}

/// Write `Syntax/Nodes/*.bd`, `Syntax/Nodes.bd` barrel, `_inventory.txt`, and thin `Syntax.bd`.
pub fn emit_syntax_sdk(
    compiler_sdk_beskid_dir: &Path,
    analysis_src: &Path,
) -> Result<SyntaxNodesGenReport, std::io::Error> {
    let files = syntax_helpers::load_syntax_files(analysis_src)?;
    let helpers = syntax_helpers::build_helper_paths(&files);
    let (decls, skipped_generics) = collect_declarations(analysis_src, Some(&helpers))?;

    let syntax_dir = compiler_sdk_beskid_dir.join("Syntax");
    let nodes_dir = syntax_dir.join("Nodes");
    fs::create_dir_all(&nodes_dir)?;

    for hname in &helpers.helper_emit_order {
        if hname == "NodeList" {
            continue;
        }
        let body = if let Some(el_path) = helpers.list_helpers.get(hname) {
            syntax_helpers::emit_list_enum(hname, el_path)
        } else if let Some(inner_path) = helpers.opt_helpers.get(hname) {
            syntax_helpers::emit_optional_enum(hname, inner_path)
        } else {
            continue;
        };
        fs::write(nodes_dir.join(format!("{hname}.bd")), body)?;
    }

    let reflect_rs = analysis_src.join("compiler_sdk_reflect.rs");
    let traversal_names =
        crate::syntax_traversal::emit_traversal_sdk(&nodes_dir, analysis_src, &reflect_rs)?;

    let type_names: Vec<String> = decls
        .keys()
        .filter(|k| !crate::syntax_traversal::is_host_only_type(k))
        .cloned()
        .collect();

    for (name, parsed) in &decls {
        if crate::syntax_traversal::is_host_only_type(name) {
            continue;
        }
        let body = emit_type_bd(name, parsed);
        let mut out = String::new();
        out.push_str(BANNER);
        out.push('\n');
        out.push_str(&body);
        out.push('\n');
        let path = nodes_dir.join(format!("{name}.bd"));
        fs::write(path, out)?;
    }

    // `_inventory.txt` — one logical type name per line (sorted via BTreeMap iteration).
    let inv_path = nodes_dir.join("_inventory.txt");
    let inv_body = type_names.join("\n") + "\n";
    fs::write(inv_path, &inv_body)?;

    let mut barrel_names: Vec<String> = traversal_names.iter().cloned().collect();
    for h in &helpers.helper_emit_order {
        if h == "NodeList" || traversal_names.contains(h) {
            continue;
        }
        barrel_names.push(h.clone());
    }
    let mut extra: Vec<String> = decls
        .keys()
        .filter(|k| {
            !crate::syntax_traversal::is_host_only_type(k)
                && !helpers.helper_emit_order.iter().any(|h| h == *k)
                && !traversal_names.contains(*k)
        })
        .cloned()
        .collect();
    extra.sort();
    barrel_names.extend(extra);

    // Barrel: `Syntax/Nodes.bd`
    let mut barrel = String::new();
    barrel.push_str(BANNER);
    barrel.push('\n');
    for name in &barrel_names {
        barrel.push_str(&format!(
            "pub mod {}.{};\n",
            SYNTAX_NODES_MODULE_PREFIX, name
        ));
    }
    fs::write(syntax_dir.join("Nodes.bd"), barrel)?;

    // Thin `Syntax.bd` (no `ReflectStub` — lists / optionals are concrete under Syntax/Nodes/).
    let syntax_bd =
        r#"// CHECKED IN: regenerated by packages/compiler-sdk/regen_mod_sdk_surfaces.sh
// Rust sources in beskid_analysis are authoritative; nested shapes live under Syntax/Nodes/.

pub mod Beskid.Syntax.Nodes;

// Hand-maintained facade ------------------------------------------------------
// Immutable syntax node views for capture keys and typed emit construction (Mod SDK).
// Host supplies concrete trees; this package carries stable layout/version metadata only.

// Facade contract version aligned with platform-spec Beskid.Syntax hub.
pub string SyntaxFacadeVersion() {
    return "0.4.0";
}
"#
        .to_string();
    fs::write(compiler_sdk_beskid_dir.join("Syntax.bd"), syntax_bd)?;

    // Remove stale `*.bd` from prior generator runs (helper renames, mapping fixes).
    let mut expected_bd: BTreeSet<String> = traversal_names;
    expected_bd.extend(
        helpers
            .helper_emit_order
            .iter()
            .cloned()
            .filter(|h| h != "NodeList"),
    );
    expected_bd.extend(
        decls
            .keys()
            .cloned()
            .filter(|k| !crate::syntax_traversal::is_host_only_type(k)),
    );
    for entry in fs::read_dir(&nodes_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension() != Some(OsStr::new("bd")) {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if !expected_bd.contains(stem) {
            fs::remove_file(&path)?;
        }
    }

    Ok(SyntaxNodesGenReport {
        type_names,
        skipped_generics,
        skipped_opaque_paths: Vec::new(),
    })
}

fn emit_reflect_stub_doc_lines(type_name: &str, parsed: &ParsedType, stub: &str) -> Vec<String> {
    let mut out = Vec::new();
    match parsed.kind {
        TypeKind::Struct => {
            for f in &parsed.fields {
                if f.beskid_ty == stub {
                    let why = f
                        .stub_note
                        .as_deref()
                        .unwrap_or("Mod SDK placeholder (no per-field expansion).");
                    out.push(format!(
                        "/// `{type_name}.{}`: ReflectStub — {}.",
                        f.name,
                        sanitize_doc_directive_suffix(why)
                    ));
                }
            }
        }
        TypeKind::Enum => {
            for v in &parsed.variants {
                let fields: &[FieldMirror] = match &v.shape {
                    VariantShape::Unit => &[],
                    VariantShape::Tuple(fs) | VariantShape::Struct(fs) => fs.as_slice(),
                };
                for f in fields {
                    if f.beskid_ty == stub {
                        let why = f
                            .stub_note
                            .as_deref()
                            .unwrap_or("Mod SDK placeholder (no per-field expansion).");
                        out.push(format!(
                            "/// `{type_name}::{}::{}`: ReflectStub — {}.",
                            v.name,
                            f.name,
                            sanitize_doc_directive_suffix(why)
                        ));
                    }
                }
            }
        }
    }
    out
}

fn emit_type_doc_block(type_name: &str, parsed: &ParsedType) -> String {
    let stub = reflect_stub_path();
    let rust_loc = format!("crates/beskid_analysis/src/{}", parsed.source_rel_path);
    let mut lines = vec![format!(
        "/// Generated syntax node mirror: `{rust_loc}` — `{type_name}`."
    )];
    if !parsed.rust_doc_lines.is_empty() {
        lines.push("///".into());
        lines.push("/// **Rust documentation** (from mirrored type):".into());
        for d in &parsed.rust_doc_lines {
            lines.push(format!("/// {d}"));
        }
    }
    if !parsed.type_param_names.is_empty() {
        lines.push("///".into());
        lines.push("/// **Rust type parameters**:".into());
        for p in &parsed.type_param_names {
            lines.push(format!(
                "/// {}",
                doc_par_line(
                    p,
                    "Generic parameter is not expanded to a concrete Beskid type in this surface; affected payloads use ReflectStub.",
                )
            ));
        }
    }
    lines.push("///".into());
    lines.push(
        "/// Generated index uses `beskid_doc.pest` `@variant` / `@par`; struct types list field names once (`@arg` is for callables only)."
            .into(),
    );
    lines.push(crate::syntax_traversal::shape_traversal_doc_line().into());
    match parsed.kind {
        TypeKind::Struct => {
            if parsed.fields.is_empty() {
                lines.push("/// Marker struct with no fields.".into());
            } else {
                let names = parsed
                    .fields
                    .iter()
                    .map(|f| format!("`{}`", f.name))
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!("/// Struct fields (see declaration): {names}."));
            }
        }
        TypeKind::Enum => {
            for v in &parsed.variants {
                lines.push(format!(
                    "/// {}",
                    doc_variant_line(&v.name, &variant_index_suffix(&v.shape))
                ));
            }
        }
    }
    let stub_lines = emit_reflect_stub_doc_lines(type_name, parsed, stub);
    if !stub_lines.is_empty() {
        lines.push("///".into());
        lines.push("/// **ReflectStub** fields (opaque in this shape):".into());
        lines.extend(stub_lines);
    }
    lines.join("\n") + "\n"
}

fn push_field_doc_lines(indent: &str, rust_doc_lines: &[String], out: &mut Vec<String>) {
    for d in rust_doc_lines {
        let t = d.trim();
        if !t.is_empty() {
            out.push(format!("{indent}/// {t}"));
        }
    }
}

fn format_variant_lines(v: &EnumVariantMirror) -> Vec<String> {
    match &v.shape {
        VariantShape::Unit => vec![format!("    {},", v.name)],
        VariantShape::Tuple(fields) | VariantShape::Struct(fields) => {
            if fields.is_empty() {
                return vec![format!("    {},", v.name)];
            }
            let mut out = vec![format!("    {}(", v.name)];
            for f in fields {
                push_field_doc_lines("        ", &f.rust_doc_lines, &mut out);
                out.push(format!("        {} {},", f.beskid_ty, f.name));
            }
            out.push("    ),".to_string());
            out
        }
    }
}

fn emit_type_bd(name: &str, parsed: &ParsedType) -> String {
    let doc = emit_type_doc_block(name, parsed);
    let decl = match parsed.kind {
        TypeKind::Struct => {
            if parsed.fields.is_empty() {
                format!("pub type {name} {{\n}}")
            } else {
                let mut lines: Vec<String> = Vec::new();
                for f in &parsed.fields {
                    push_field_doc_lines("    ", &f.rust_doc_lines, &mut lines);
                    lines.push(format!("    {} {},", f.beskid_ty, f.name));
                }
                format!("pub type {name} {{\n{}\n}}", lines.join("\n"))
            }
        }
        TypeKind::Enum => {
            let mut lines: Vec<String> = Vec::new();
            for v in &parsed.variants {
                push_field_doc_lines("    ", &v.rust_doc_lines, &mut lines);
                lines.extend(format_variant_lines(v));
            }
            format!("pub enum {name}\n{{\n{}\n}}", lines.join("\n"))
        }
    };
    doc + &decl
}

/// Parse `ReflectSdkNodeKind` variant names from `compiler_sdk_reflect.rs` (set equality tests).
pub fn reflect_sdk_node_kind_names(reflect_rs: &Path) -> Result<BTreeSet<String>, std::io::Error> {
    let text = fs::read_to_string(reflect_rs)?;
    let mut out = BTreeSet::new();
    let mut in_enum = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with("pub enum ReflectSdkNodeKind") {
            in_enum = true;
            continue;
        }
        if in_enum {
            if t.starts_with('}') && !t.starts_with("},") {
                break;
            }
            if let Some(name) = t.strip_suffix(',') {
                let name = name.trim();
                if name.is_empty() || name.starts_with("//") {
                    continue;
                }
                if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
                    out.insert(name.to_string());
                }
            }
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    fn trim_field_token(tok: &str) -> &str {
        tok.trim_end_matches([',', ')', ';'])
    }

    /// True for legacy `f0`/`f1` positional placeholders (not `f32`/`f64` types).
    fn is_fnumeric_placeholder_field(tok: &str) -> bool {
        let w = trim_field_token(tok);
        if w == "f32" || w == "f64" {
            return false;
        }
        let Some(rest) = w.strip_prefix('f') else {
            return false;
        };
        !rest.is_empty() && rest.chars().all(|c| c.is_ascii_digit())
    }

    #[test]
    fn inventory_matches_reflect_sdk_node_kinds() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let reflect_rs = manifest.join("../beskid_analysis/src/compiler_sdk_reflect.rs");
        let inv: BTreeSet<String> = inventory_syntax_type_names(&analysis_src)
            .expect("inventory")
            .into_iter()
            .collect();
        let kinds = reflect_sdk_node_kind_names(&reflect_rs).expect("reflect parse");
        let kinds_needing_shapes: BTreeSet<_> = kinds
            .iter()
            .filter(|k| *k != "Node")
            .cloned()
            .collect();
        assert!(
            kinds_needing_shapes.is_subset(&inv),
            "every ReflectSdkNodeKind (except contract-only Node) must have a generated shape file; missing: {:?}",
            kinds_needing_shapes.difference(&inv).collect::<Vec<_>>()
        );
        // `AssignOp` is nested under `AssignExpression` (no standalone `NodeKind` today).
        let allowed_extra: BTreeSet<String> = [
            "AssignOp",
            "FieldKind",
            "InjectQualifier",
            "RegistrationLifetime",
            "ScopeHookKind",
        ]
        .iter()
        .map(|s| (*s).to_string())
        .collect();
        let extras: BTreeSet<_> = inv.difference(&kinds).cloned().collect();
        assert!(
            extras.is_subset(&allowed_extra),
            "unexpected syntax types not listed in ReflectSdkNodeKind: {:?}",
            extras.difference(&allowed_extra).collect::<Vec<_>>()
        );
    }

    #[test]
    fn golden_syntax_nodes_inventory_matches_scan() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let names = inventory_syntax_type_names(&analysis_src).expect("inventory");
        let got = names.join("\n") + "\n";
        let expected = include_str!("../tests/expected/syntax_nodes_inventory.txt");
        assert_eq!(
            got, expected,
            "update tests/expected/syntax_nodes_inventory.txt after adding/removing syntax surface types"
        );
    }

    /// Generated `Syntax/Nodes/*.bd` must not use legacy `f0`/`f1` positional field names.
    #[test]
    fn syntax_node_emission_avoids_fnumeric_field_names() {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let files = syntax_helpers::load_syntax_files(&analysis_src).expect("load");
        let helpers = syntax_helpers::build_helper_paths(&files);
        let (decls, _) = collect_declarations(&analysis_src, Some(&helpers)).expect("collect");
        for (name, parsed) in &decls {
            let text = emit_type_bd(name, parsed);
            for line in text.lines() {
                let trimmed = line.trim_start();
                if trimmed.starts_with("///") {
                    continue;
                }
                for tok in line.split_whitespace() {
                    assert!(
                        !is_fnumeric_placeholder_field(tok),
                        "legacy fN field placeholder in emitted `{name}`: {line}"
                    );
                }
            }
        }
    }

    /// With list/optional helpers enabled, syntax node bodies must not reference the removed
    /// `Syntax.ReflectStub` placeholder (opaque shapes still map to the same string elsewhere).
    #[test]
    fn syntax_node_emission_avoids_syntax_reflect_stub_path() {
        let stub = reflect_stub_path();
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        let analysis_src = manifest.join("../beskid_analysis/src");
        let files = syntax_helpers::load_syntax_files(&analysis_src).expect("load");
        let helpers = syntax_helpers::build_helper_paths(&files);
        let (decls, _) = collect_declarations(&analysis_src, Some(&helpers)).expect("collect");
        for (name, parsed) in &decls {
            let text = emit_type_bd(name, parsed);
            assert!(
                !text.contains(stub),
                "emitted `{name}` must not use {stub}; use concrete Nodes helpers instead"
            );
        }
    }
}
