[package]
name = "beskid_aot"
version = "0.1.0"
edition = "2024"

[dependencies]
beskid_abi = { path = "../beskid_abi" }
beskid_codegen = { path = "../beskid_codegen" }
beskid_analysis = { path = "../beskid_analysis" }
beskid_queries = { path = "../beskid_queries", features = ["persistence"] }
beskid_pipeline = { path = "../beskid_pipeline" }
cranelift-codegen = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
thiserror = "2"
tempfile = "3"
cc = "1"
ar = "0.9"
object = "0.37.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
beskid_pest_gen = { path = "../beskid_pest_gen" }
cargo-cross = { workspace = true }

[dev-dependencies]
beskid_codegen = { path = "../beskid_codegen" }
