//! Human-readable labels for stable pipeline phase ids.

use beskid_pipeline::phases;

/// Short title for a pipeline phase id shown in the CLI progress UI.
pub fn phase_label(id: &str) -> &str {
    match id {
        phases::RESOLVE_MANIFEST => "Resolve manifest",
        phases::RESOLVE_GRAPH => "Resolve dependency graph",
        phases::WORKSPACE_GRAPH_CHANGED => "Refresh workspace graph",
        phases::WORKSPACE_MATERIALIZE => "Materialize dependencies",
        phases::WORKSPACE_MATERIALIZE_LOCAL => "Copy project sources",
        phases::WORKSPACE_MATERIALIZE_PATH_DEPS => "Copy path dependencies",
        phases::WORKSPACE_MATERIALIZE_REGISTRY => "Fetch registry packages",
        phases::WORKSPACE_MATERIALIZE_LOCKFILE => "Sync lockfile",
        phases::PROGRAM_ASSEMBLE => "Assemble program",
        phases::PARSE => "Parse sources",
        phases::MACRO_EXPAND => "Expand macros",
        phases::MOD_LOAD => "Load compiler mods",
        phases::MOD_COLLECT => "Collect mod targets",
        phases::MOD_GENERATE => "Generate from mods",
        phases::SYNTAX_GENERATION => "Syntax generation",
        phases::SEMANTIC => "Semantic analysis",
        phases::SEMANTIC_DEFINITIONS => "Collect definitions",
        phases::SEMANTIC_CONTROL_FLOW => "Check control flow",
        phases::SEMANTIC_NAME_RESOLUTION => "Resolve names",
        phases::SEMANTIC_VISIBILITY => "Check modules and visibility",
        phases::SEMANTIC_CONTRACTS => "Check contracts and methods",
        phases::SEMANTIC_ERROR_HANDLING => "Check error handling",
        phases::SEMANTIC_TYPE_CHECK => "Type check",
        phases::SEMANTIC_NAMING_STYLE => "Check naming style",
        phases::SEMANTIC_SNAPSHOT => "Semantic snapshot",
        phases::COMPOSITION_RESOLVE => "Resolve composition",
        phases::MOD_ANALYZE => "Analyze with mods",
        phases::MOD_REWRITE => "Rewrite with mods",
        phases::MOD_GLUE => "Run glue mods",
        phases::LOWER_READY => "Prepare lowering",
        phases::LOWER => "Lower to HIR",
        phases::LOWER_AST => "Lower AST to HIR",
        phases::LOWER_RESOLVE_PASS1 => "Resolve (pass 1)",
        phases::LOWER_NORMALIZE => "Normalize HIR",
        phases::LOWER_RESOLVE => "Resolve (pass 2)",
        phases::LOWER_TYPE_CHECK => "Type check",
        phases::CODEGEN_CLIF => "Generate CLIF",
        phases::AOT_EMIT_OBJECT => "Emit object code",
        phases::JIT_EMIT => "JIT compile",
        phases::JIT_FINALIZE => "Finalize JIT module",
        phases::AOT_RUNTIME => "Load runtime library",
        phases::AOT_LINK => "Link native artifact",
        _ => id,
    }
}
