[package]
name = "beskid_runtime_bridge"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
beskid_runtime = { path = "../beskid_runtime" }
beskid_host = { path = "../beskid_host", optional = true }

[features]
default = ["host"]
host = ["dep:beskid_host"]

[build-dependencies]
beskid_manifest = { path = "../beskid_manifest" }
