[package]
name = "beskid_runtime_bridge"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
beskid_runtime = { path = "../beskid_runtime" }
beskid_host = { path = "../beskid_host", optional = true }
beskid_runtime_handlers = { path = "../beskid_runtime_handlers", optional = true }

[features]
default = ["host", "language_handlers"]
host = ["dep:beskid_host"]
language_handlers = ["dep:beskid_runtime_handlers"]

[build-dependencies]
beskid_manifest = { path = "../beskid_manifest" }
