//! Curated `#[beskid_reflect]` enums for Mod SDK `.bd` generation (`beskid_ast_reflect_gen`).
//!
//! `ReflectSdkNodeKind` / `ReflectSdkHirNodeKind` mirror the `node_kinds!` expansions in
//! `query/mod.rs` — update both together when adding node kinds.

/// Syntax / AST query classification tokens (mirrors [`crate::syntax_query::NodeKind`]).
#[beskid_ast_derive::beskid_reflect]
pub enum ReflectSdkNodeKind {
    Program,
    Node,
    FunctionDefinition,
    ConstantDefinition,
    MethodDefinition,
    TypeDefinition,
    EnumDefinition,
    EnumVariant,
    ContractDefinition,
    TestDefinition,
    TestMetaSection,
    TestMetadataEntry,
    TestSkipSection,
    TestSkipEntry,
    ContractNode,
    ContractMethodSignature,
    ContractEmbedding,
    Attribute,
    AttributeDeclaration,
    AttributeTarget,
    AttributeParameter,
    AttributeArgument,
    ModuleDeclaration,
    InlineModule,
    UseDeclaration,
    Block,
    Statement,
    LetStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,
    WhileStatement,
    ForStatement,
    IfStatement,
    ElseBranch,
    ExpressionStatement,
    ExtendTypeDefinition,
    RangeExpression,
    SpawnExpression,
    Expression,
    AssignExpression,
    BinaryExpression,
    BinaryOp,
    UnaryExpression,
    UnaryOp,
    CallExpression,
    MemberExpression,
    LiteralExpression,
    PathExpression,
    StructLiteralExpression,
    IndexExpression,
    ArrayLiteralExpression,
    CodeStringLiteral,
    CodeStringSegment,
    ClifBlockExpression,
    EnumConstructorExpression,
    BlockExpression,
    GroupedExpression,
    TryExpression,
    LambdaExpression,
    LambdaParameter,
    MatchExpression,
    MatchArm,
    Pattern,
    EnumPattern,
    Literal,
    Identifier,
    Type,
    Path,
    PathSegment,
    EnumPath,
    Field,
    Parameter,
    PrimitiveType,
    StructLiteralField,
    StringLiteralPart,
    Visibility,
    MacroFragmentKind,
    MacroParameter,
    MacroDefinition,
    MacroInvocation,
    MacroMetavariable,
    HostDefinition,
    HostBodyItem,
    RegistryBlock,
    RegistryEntry,
    ScopeDefinition,
    ScopeHook,
    WithStatement,
    LaunchStatement,
}

/// HIR query classification tokens (mirrors [`crate::syntax_query::HirNodeKind`]).
#[beskid_ast_derive::beskid_reflect]
pub enum ReflectSdkHirNodeKind {
    Program,
    Module,
    Item,
    FunctionDefinition,
    MethodDefinition,
    TypeDefinition,
    EnumDefinition,
    EnumVariant,
    ContractDefinition,
    TestDefinition,
    TestMetaSection,
    TestMetadataEntry,
    TestSkipSection,
    TestSkipEntry,
    ContractNode,
    ContractMethodSignature,
    ContractEmbedding,
    Attribute,
    AttributeDeclaration,
    AttributeTarget,
    AttributeParameter,
    AttributeArgument,
    ModuleDeclaration,
    InlineModule,
    UseDeclaration,
    Block,
    Statement,
    LetStatement,
    ReturnStatement,
    BreakStatement,
    ContinueStatement,
    WhileStatement,
    ForStatement,
    IfStatement,
    ElseBranch,
    ExpressionStatement,
    ExtendTypeDefinition,
    RangeExpression,
    SpawnExpression,
    Expression,
    AssignExpression,
    BinaryExpression,
    BinaryOp,
    UnaryExpression,
    UnaryOp,
    CallExpression,
    MemberExpression,
    LiteralExpression,
    PathExpression,
    StructLiteralExpression,
    IndexExpression,
    ArrayLiteralExpression,
    CodeStringLiteral,
    EnumConstructorExpression,
    BlockExpression,
    GroupedExpression,
    TryExpression,
    LambdaExpression,
    LambdaParameter,
    MatchExpression,
    MatchArm,
    Pattern,
    EnumPattern,
    Literal,
    Identifier,
    Type,
    Path,
    PathSegment,
    EnumPath,
    Field,
    Parameter,
    PrimitiveType,
    StructLiteralField,
    Visibility,
}

/// Emit-plane contribution categories for the Mod SDK (host-owned payloads).
#[beskid_ast_derive::beskid_reflect]
pub enum ReflectSdkEmitContributionKind {
    Metadata,
    LoweringDirective,
    DiagnosticAttachment,
}

/// Top-level syntax item kinds a Generator may contribute (typed merge plane).
#[beskid_ast_derive::beskid_reflect]
pub enum ReflectSdkSyntaxContributionItem {
    ContractDefinition,
    TypeDefinition,
    FunctionDefinition,
}

/// Internal mod entrypoint binding categories (`Beskid.Compiler.InternalSymbol`).
#[beskid_ast_derive::beskid_reflect]
pub enum ReflectSdkInternalSymbolType {
    Callable,
}

/// Read-only compilation snapshot planes exposed to queries.
#[beskid_ast_derive::beskid_reflect]
pub enum ReflectSdkCompilationSnapshotPlane {
    SyntaxTree,
    Hir,
    SemanticSnapshot,
}
