INCLUDE beskid_runtime_abi_v5_x86_64_pc_windows_msvc.inc

OPTION PROLOGUE:NONE
OPTION EPILOGUE:NONE

.code

PUBLIC beskid_arch_v5_context_init
beskid_arch_v5_context_init PROC
    mov r10, BESKID_CONTEXT_INIT_RETURN_TRAMPOLINE_STACK_OPERAND
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RBX_OFFSET], 0
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RBP_OFFSET], 0
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RDI_OFFSET], 0
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RSI_OFFSET], 0
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R12_OFFSET], r9
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R13_OFFSET], 0
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R14_OFFSET], 0
    mov QWORD PTR [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R15_OFFSET], 0
    pxor xmm0, xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM6_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM7_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM8_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM9_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM10_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM11_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM12_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM13_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM14_OFFSET], xmm0
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM15_OFFSET], xmm0
    mov rax, rdx
    and rax, -16
    sub rax, 40
    mov [rax], r10
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RSP_OFFSET], rax
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RIP_OFFSET], r8
    ret
beskid_arch_v5_context_init ENDP

PUBLIC beskid_arch_v5_context_switch
beskid_arch_v5_context_switch PROC
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RBX_OFFSET], rbx
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RBP_OFFSET], rbp
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RDI_OFFSET], rdi
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RSI_OFFSET], rsi
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R12_OFFSET], r12
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R13_OFFSET], r13
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R14_OFFSET], r14
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R15_OFFSET], r15
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RSP_OFFSET], rsp
    lea rax, context_resume
    mov [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RIP_OFFSET], rax
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM6_OFFSET], xmm6
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM7_OFFSET], xmm7
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM8_OFFSET], xmm8
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM9_OFFSET], xmm9
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM10_OFFSET], xmm10
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM11_OFFSET], xmm11
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM12_OFFSET], xmm12
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM13_OFFSET], xmm13
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM14_OFFSET], xmm14
    movdqu [rcx + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM15_OFFSET], xmm15

    mov r10, rdx
    mov rbx, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RBX_OFFSET]
    mov rbp, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RBP_OFFSET]
    mov rdi, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RDI_OFFSET]
    mov rsi, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RSI_OFFSET]
    mov r12, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R12_OFFSET]
    mov r13, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R13_OFFSET]
    mov r14, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R14_OFFSET]
    mov r15, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_R15_OFFSET]
    movdqu xmm6, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM6_OFFSET]
    movdqu xmm7, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM7_OFFSET]
    movdqu xmm8, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM8_OFFSET]
    movdqu xmm9, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM9_OFFSET]
    movdqu xmm10, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM10_OFFSET]
    movdqu xmm11, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM11_OFFSET]
    movdqu xmm12, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM12_OFFSET]
    movdqu xmm13, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM13_OFFSET]
    movdqu xmm14, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM14_OFFSET]
    movdqu xmm15, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_XMM15_OFFSET]
    mov rsp, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RSP_OFFSET]
    mov r11, [r10 + BESKID_X86_64_PC_WINDOWS_MSVC_CONTEXT_RIP_OFFSET]
    mov rcx, r12
    jmp r11

context_resume:
    ret
beskid_arch_v5_context_switch ENDP

END
