[package]
name = "beskid_codegen"
version = "0.1.0"
edition = "2024"

[features]
default = []
slow = []

[dependencies]
beskid_abi = { path = "../beskid_abi" }
beskid_pipeline = { path = "../beskid_pipeline" }
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-module = { workspace = true }
beskid_analysis = { path = "../beskid_analysis" }
beskid_queries = { path = "../beskid_queries" }
beskid_isle = { path = "../beskid_isle" }
beskid_runtime = { path = "../beskid_runtime" }
anyhow = "1"
thiserror = "2"

[dev-dependencies]
pest = { workspace = true }
tempfile = "3"
