use std::collections::HashMap;
use std::fmt::Write as _;

use crate::model::{DispatchEntry, ManifestRoot};

pub fn render_abi_builtins(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out, "#![allow(dead_code)]").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "use crate::abi_types::{{AbiParamKind, AbiReturnKind, BuiltinFnSpec}};"
    )
    .unwrap();
    writeln!(&mut out, "use crate::generated::symbols::{{").unwrap();
    for entry in &manifest.kernel {
        writeln!(&mut out, "    SYM_{},", symbol_const_suffix(&entry.symbol)).unwrap();
    }
    writeln!(&mut out, "}};").unwrap();
    writeln!(&mut out).unwrap();

    let mut param_arrays: HashMap<Vec<AbiParamKind>, String> = HashMap::new();
    let mut next_id = 0usize;
    let mut specs = Vec::new();

    for entry in &manifest.kernel {
        let params = manifest_param_kinds(&entry.params);
        let name = param_array_name(&params, &mut param_arrays, &mut next_id);
        let returns = manifest_return_abi(&entry.returns);
        specs.push((symbol_const_suffix(&entry.symbol), name, returns));
    }

    for (params, name) in param_arrays.iter() {
        let formatted = format_param_array(params);
        writeln!(
            &mut out,
            "const {name}: [AbiParamKind; {len}] = {formatted};",
            len = params.len()
        )
        .unwrap();
    }
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "/// Kernel direct imports and interop dispatch entrypoints (ABI v{}).",
        manifest.manifest.abi_version
    )
    .unwrap();
    writeln!(&mut out, "pub const BUILTIN_SPECS: &[BuiltinFnSpec] = &[").unwrap();
    for (sym, params, returns) in specs {
        let returns = match returns {
            AbiReturnKind::Void => "AbiReturnKind::Void",
            AbiReturnKind::Ptr => "AbiReturnKind::Ptr",
            AbiReturnKind::I64 => "AbiReturnKind::I64",
            AbiReturnKind::I32 => "AbiReturnKind::I32",
            AbiReturnKind::Never => "AbiReturnKind::Never",
        };
        if params == "EMPTY" {
            writeln!(
                &mut out,
                "    BuiltinFnSpec {{ symbol: SYM_{sym}, params: &[], returns: {returns} }},"
            )
            .unwrap();
        } else {
            writeln!(
                &mut out,
                "    BuiltinFnSpec {{ symbol: SYM_{sym}, params: &{params}, returns: {returns} }},"
            )
            .unwrap();
        }
    }
    writeln!(&mut out, "];").unwrap();
    out
}

pub fn render_abi_symbols(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    let mut all_symbols: Vec<(String, String)> = manifest
        .kernel
        .iter()
        .map(|entry| (symbol_const_suffix(&entry.symbol), entry.symbol.clone()))
        .collect();
    for group in dispatch_groups(manifest) {
        for entry in group {
            all_symbols.push((
                symbol_const_suffix(&entry.legacy_symbol),
                entry.legacy_symbol.clone(),
            ));
        }
    }
    all_symbols.sort_by(|a, b| a.1.cmp(&b.1));
    all_symbols.dedup_by(|a, b| a.1 == b.1);

    for (const_suffix, symbol) in &all_symbols {
        if let Some(doc) = dispatch_doc(manifest, symbol) {
            writeln!(&mut out, "/// {doc}").unwrap();
        }
        writeln!(
            &mut out,
            "pub const SYM_{const_suffix}: &str = \"{symbol}\";"
        )
        .unwrap();
    }

    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// User-facing FFI layout band for callback registration tables (independent of"
    )
    .unwrap();
    writeln!(&mut out, "/// [`crate::BESKID_RUNTIME_ABI_VERSION`]).").unwrap();
    writeln!(&mut out, "pub const BESKID_USER_FFI_LAYOUT_BAND: u32 = 1;").unwrap();
    writeln!(&mut out).unwrap();

    writeln!(
        &mut out,
        "/// Kernel exports registered by the JIT / AOT linker for ABI v{}.",
        manifest.manifest.abi_version
    )
    .unwrap();
    writeln!(&mut out, "pub const RUNTIME_EXPORT_SYMBOLS: &[&str] = &[").unwrap();
    for entry in &manifest.kernel {
        writeln!(&mut out, "    SYM_{},", symbol_const_suffix(&entry.symbol)).unwrap();
    }
    writeln!(&mut out, "];").unwrap();
    out
}

pub fn render_dispatch_tags(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "//! Dispatch tag constants for soft runtime operations (ABI v{}).",
        manifest.manifest.abi_version
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    render_dispatch_group(&mut out, "usize", &manifest.dispatch.usize);
    render_dispatch_group(&mut out, "ptr", &manifest.dispatch.ptr);
    render_dispatch_group(&mut out, "unit", &manifest.dispatch.unit);
    render_dispatch_group(&mut out, "i64", &manifest.dispatch.i64);

    writeln!(
        &mut out,
        "/// Total soft dispatch entries across all return groups."
    )
    .unwrap();
    let total = manifest.dispatch.usize.len()
        + manifest.dispatch.ptr.len()
        + manifest.dispatch.unit.len()
        + manifest.dispatch.i64.len();
    writeln!(&mut out, "pub const DISPATCH_ENTRY_COUNT: usize = {total};").unwrap();
    out
}

pub fn render_dispatch_lookup(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "//! Maps legacy runtime symbols to manifest dispatch tags and return groups."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "use crate::generated::dispatch_tags::{{{}}};",
        dispatch_tag_imports(manifest)
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// v3 [`RuntimeInteropEnvelope`](https://beskid-lang.org/platform-spec/language-meta/interop/interop-contracts/adr/0004-dispatch-envelope-layout/) header size in bytes."
    )
    .unwrap();
    writeln!(
        &mut out,
        "pub const DISPATCH_ENVELOPE_HEADER_SIZE: i32 = 16;"
    )
    .unwrap();
    writeln!(&mut out, "pub const DISPATCH_TYPE_DESC_OFFSET: i32 = 0;").unwrap();
    writeln!(&mut out, "pub const DISPATCH_TAG_OFFSET: i32 = 8;").unwrap();
    writeln!(&mut out, "pub const DISPATCH_PAD_OFFSET: i32 = 12;").unwrap();
    writeln!(&mut out, "pub const DISPATCH_PAYLOAD_OFFSET: i32 = 16;").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(&mut out, "pub enum DispatchReturnGroup {{").unwrap();
    writeln!(&mut out, "    Unit,").unwrap();
    writeln!(&mut out, "    Ptr,").unwrap();
    writeln!(&mut out, "    Usize,").unwrap();
    writeln!(&mut out, "    I64,").unwrap();
    writeln!(&mut out, "}}").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "#[derive(Debug, Clone, Copy, PartialEq, Eq)]").unwrap();
    writeln!(&mut out, "pub struct DispatchRoute {{").unwrap();
    writeln!(&mut out, "    pub tag: i32,").unwrap();
    writeln!(&mut out, "    pub group: DispatchReturnGroup,").unwrap();
    writeln!(&mut out, "}}").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// Resolve a legacy runtime symbol to its manifest dispatch route, if any."
    )
    .unwrap();
    writeln!(
        &mut out,
        "pub fn dispatch_route_for_symbol(symbol: &str) -> Option<DispatchRoute> {{"
    )
    .unwrap();
    writeln!(&mut out, "    match symbol {{").unwrap();
    for (group, entries) in dispatch_lookup_groups(manifest) {
        let group_ident = dispatch_group_ident(group);
        for entry in entries {
            writeln!(
                &mut out,
                "        \"{symbol}\" => Some(DispatchRoute {{ tag: TAG_{tag}, group: DispatchReturnGroup::{group_ident} }}),",
                symbol = entry.legacy_symbol,
                tag = tag_const_name(&entry.name),
                group_ident = group_ident,
            )
            .unwrap();
        }
    }
    writeln!(&mut out, "        _ => None,").unwrap();
    writeln!(&mut out, "    }}").unwrap();
    writeln!(&mut out, "}}").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// True when `symbol` is a soft dispatch op (not a direct kernel export)."
    )
    .unwrap();
    writeln!(
        &mut out,
        "pub fn is_dispatch_symbol(symbol: &str) -> bool {{"
    )
    .unwrap();
    writeln!(&mut out, "    dispatch_route_for_symbol(symbol).is_some()").unwrap();
    writeln!(&mut out, "}}").unwrap();
    out
}

pub fn render_jit_kernel_registration(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "use beskid_abi::generated::symbols::{{").unwrap();
    for entry in &manifest.kernel {
        writeln!(&mut out, "    SYM_{},", symbol_const_suffix(&entry.symbol)).unwrap();
    }
    writeln!(&mut out, "}};").unwrap();
    writeln!(&mut out, "use cranelift_jit::JITBuilder;").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// Register kernel exports from [`beskid_abi::RUNTIME_EXPORT_SYMBOLS`]."
    )
    .unwrap();
    writeln!(
        &mut out,
        "pub fn register_kernel_exports(builder: &mut JITBuilder) {{"
    )
    .unwrap();
    for entry in &manifest.kernel {
        writeln!(
            &mut out,
            "    builder.symbol(SYM_{}, beskid_runtime::{} as *const u8);",
            symbol_const_suffix(&entry.symbol),
            entry.symbol
        )
        .unwrap();
    }
    writeln!(&mut out, "}}").unwrap();
    out
}

pub fn render_link_anchor(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// Force the linker to retain kernel exports referenced by generated code."
    )
    .unwrap();
    writeln!(&mut out, "pub fn anchor_kernel_exports() {{").unwrap();
    for entry in &manifest.kernel {
        writeln!(
            &mut out,
            "    let _ = beskid_runtime::{} as usize;",
            entry.symbol
        )
        .unwrap();
    }
    writeln!(&mut out, "}}").unwrap();
    out
}

fn dispatch_lookup_groups(manifest: &ManifestRoot) -> [(&str, &[DispatchEntry]); 4] {
    [
        ("unit", &manifest.dispatch.unit),
        ("ptr", &manifest.dispatch.ptr),
        ("usize", &manifest.dispatch.usize),
        ("i64", &manifest.dispatch.i64),
    ]
}

fn dispatch_group_ident(group: &str) -> &'static str {
    match group {
        "unit" => "Unit",
        "ptr" => "Ptr",
        "usize" => "Usize",
        "i64" => "I64",
        _ => "I64",
    }
}

fn render_dispatch_group(out: &mut String, group: &str, entries: &[DispatchEntry]) {
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// Number of `{group}` dispatch handlers declared in the manifest."
    )
    .unwrap();
    writeln!(
        out,
        "pub const DISPATCH_{}_COUNT: usize = {};",
        group.to_uppercase(),
        entries.len()
    )
    .unwrap();
    for entry in entries {
        writeln!(
            out,
            "/// `{symbol}` → legacy handler `{legacy}`",
            symbol = entry.name,
            legacy = entry.legacy_symbol
        )
        .unwrap();
        writeln!(
            out,
            "pub const TAG_{}: i32 = {};",
            tag_const_name(&entry.name),
            entry.tag
        )
        .unwrap();
    }
}

pub fn render_analysis_builtins(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "define_builtins! {{").unwrap();

    for intrinsic in &manifest.intrinsic {
        write_analysis_entry(
            &mut out,
            &intrinsic.path,
            &intrinsic.symbol,
            &intrinsic.params,
            &intrinsic.returns,
            intrinsic.injected,
        );
    }

    for entry in &manifest.kernel {
        if entry.beskid_path.is_empty() {
            continue;
        }
        write_analysis_entry(
            &mut out,
            &entry.beskid_path,
            &entry.symbol,
            &entry.params,
            &entry.returns,
            entry.injected,
        );
    }

    for group in dispatch_groups(manifest) {
        for entry in group {
            if entry.beskid_path.is_empty() {
                continue;
            }
            write_analysis_entry(
                &mut out,
                &entry.beskid_path,
                &entry.legacy_symbol,
                &entry.params,
                &entry.returns,
                entry.injected,
            );
        }
    }

    writeln!(&mut out, "}}").unwrap();
    out
}

fn write_analysis_entry(
    out: &mut String,
    path: &[String],
    symbol: &str,
    params: &[String],
    returns: &str,
    injected: bool,
) {
    let path_lit = path
        .iter()
        .map(|segment| format!("\"{segment}\""))
        .collect::<Vec<_>>()
        .join(", ");
    let params_lit = params
        .iter()
        .map(|param| analysis_type_ident(param))
        .collect::<Vec<_>>()
        .join(", ");
    let returns_lit = analysis_type_ident(returns);
    writeln!(out, "    &[{path_lit}] => {{").unwrap();
    writeln!(out, "        symbol: \"{symbol}\",").unwrap();
    writeln!(out, "        params: [{params_lit}],").unwrap();
    writeln!(out, "        returns: {returns_lit},").unwrap();
    writeln!(out, "        injected: {injected},").unwrap();
    writeln!(out, "    }},").unwrap();
}

fn dispatch_groups<'a>(manifest: &'a ManifestRoot) -> [&'a [DispatchEntry]; 4] {
    [
        &manifest.dispatch.usize,
        &manifest.dispatch.ptr,
        &manifest.dispatch.unit,
        &manifest.dispatch.i64,
    ]
}

fn dispatch_doc(manifest: &ManifestRoot, symbol: &str) -> Option<String> {
    for entry in manifest.kernel.iter() {
        if entry.symbol == symbol {
            return None;
        }
    }
    for group in dispatch_groups(manifest) {
        for entry in group {
            if entry.legacy_symbol == symbol {
                return Some(format!(
                    "Legacy runtime symbol for dispatch tag `{}` ({})",
                    entry.name, entry.legacy_symbol
                ));
            }
        }
    }
    None
}

fn tag_const_name(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_uppercase() && !out.is_empty() {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
    }
    out
}

fn symbol_const_suffix(symbol: &str) -> String {
    match symbol {
        "beskid_runtime_abi_version" => "ABI_VERSION".to_string(),
        "fiber_join_status" => "FIBER_JOIN".to_string(),
        "channel_receive_status" => "CHANNEL_RECEIVE".to_string(),
        "hub_wait_receive_status" => "HUB_WAIT_RECEIVE".to_string(),
        other => other
            .chars()
            .map(|ch| {
                if ch.is_ascii_alphanumeric() {
                    ch.to_ascii_uppercase()
                } else {
                    '_'
                }
            })
            .collect(),
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
enum AbiParamKind {
    Ptr,
    I64,
}

#[derive(Clone, Copy)]
enum AbiReturnKind {
    Void,
    Ptr,
    I64,
    I32,
    Never,
}

fn manifest_param_kinds(params: &[String]) -> Vec<AbiParamKind> {
    params
        .iter()
        .map(|param| match param.as_str() {
            "ptr" | "string" => AbiParamKind::Ptr,
            _ => AbiParamKind::I64,
        })
        .collect()
}

fn manifest_return_abi(returns: &str) -> AbiReturnKind {
    match returns {
        "unit" | "void" => AbiReturnKind::Void,
        "ptr" => AbiReturnKind::Ptr,
        "never" => AbiReturnKind::Never,
        "i32" => AbiReturnKind::I32,
        _ => AbiReturnKind::I64,
    }
}

fn analysis_type_ident(param: &str) -> String {
    match param {
        "string" => "String".to_string(),
        "ptr" => "Ptr".to_string(),
        "usize" => "Usize".to_string(),
        "u64" | "i64" | "i32" => "U64".to_string(),
        "unit" | "void" => "Unit".to_string(),
        "never" => "Never".to_string(),
        other => other.to_string(),
    }
}

fn param_array_name(
    params: &[AbiParamKind],
    seen: &mut HashMap<Vec<AbiParamKind>, String>,
    next_id: &mut usize,
) -> String {
    if let Some(name) = seen.get(params) {
        return name.clone();
    }
    let name = if params.is_empty() {
        "EMPTY".to_string()
    } else if params.len() == 2 && params[0] == AbiParamKind::Ptr && params[1] == AbiParamKind::Ptr
    {
        "PTR_PTR".to_string()
    } else if params.len() == 1 && params[0] == AbiParamKind::Ptr {
        "PTR_ONLY".to_string()
    } else if params.len() == 1 && params[0] == AbiParamKind::I64 {
        "I64_ONLY".to_string()
    } else {
        let generated = format!("PARAMS_{next_id}");
        *next_id += 1;
        generated
    };
    seen.insert(params.to_vec(), name.clone());
    name
}

pub fn render_runtime_dispatch_table(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out, "#![allow(clippy::too_many_lines)]").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(&mut out, "use core::hint::unreachable_unchecked;").unwrap();
    writeln!(&mut out, "use beskid_abi::BeskidStr;").unwrap();
    writeln!(
        &mut out,
        "use beskid_abi::{{{}}};",
        dispatch_tag_imports(manifest)
    )
    .unwrap();
    writeln!(&mut out).unwrap();

    let groups: [(&str, &[DispatchEntry], u32); 4] = [
        ("usize", &manifest.dispatch.usize, 0),
        ("ptr", &manifest.dispatch.ptr, 1),
        ("unit", &manifest.dispatch.unit, 2),
        ("i64", &manifest.dispatch.i64, 3),
    ];

    for (group, entries, group_id) in groups {
        writeln!(
            &mut out,
            "/// Dispatch return group `{group}` (registration group id `{group_id}`)."
        )
        .unwrap();
        writeln!(
            &mut out,
            "pub const DISPATCH_GROUP_{}: u32 = {group_id};",
            group.to_uppercase()
        )
        .unwrap();
        let bitmap = valid_tags_bitmap(entries);
        writeln!(
            &mut out,
            "const VALID_TAGS_{}: u64 = {bitmap:#x};",
            group.to_uppercase()
        )
        .unwrap();
        writeln!(&mut out).unwrap();
    }

    for (group, entries, _) in groups {
        render_valid_tag_fn(&mut out, group, entries);
    }
    writeln!(&mut out).unwrap();

    render_dispatch_fn(
        &mut out,
        "dispatch_usize",
        "usize",
        &manifest.dispatch.usize,
        "try_dispatch_usize",
        "Option<usize>",
        |entry, body| {
            if entry.returns == "never" {
                format!("Some({{\n{body};\n            unreachable_unchecked()\n        }})")
            } else {
                format!("Some({{\n{body}\n        }} as usize)")
            }
        },
    );
    render_dispatch_fn(
        &mut out,
        "dispatch_ptr",
        "ptr",
        &manifest.dispatch.ptr,
        "try_dispatch_ptr",
        "Option<*mut u8>",
        |entry, body| {
            if entry.returns == "never" {
                format!("{{\n{body};\n            unreachable_unchecked()\n        }}")
            } else {
                format!("Some({{\n{body}\n        }} as *mut u8)")
            }
        },
    );
    render_dispatch_fn(
        &mut out,
        "dispatch_unit",
        "unit",
        &manifest.dispatch.unit,
        "try_dispatch_unit",
        "bool",
        |_entry, body| format!("{{\n{body};\n            true\n        }}"),
    );
    render_dispatch_fn(
        &mut out,
        "dispatch_i64",
        "i64",
        &manifest.dispatch.i64,
        "try_dispatch_i64",
        "Option<i64>",
        |entry, body| {
            if entry.returns == "never" {
                format!("{{\n{body};\n            unreachable_unchecked()\n        }}")
            } else {
                format!("Some({{\n{body}\n        }} as i64)")
            }
        },
    );

    out
}

fn dispatch_tag_imports(manifest: &ManifestRoot) -> String {
    let mut tags = Vec::new();
    for group in dispatch_groups(manifest) {
        for entry in group {
            tags.push(format!("TAG_{}", tag_const_name(&entry.name)));
        }
    }
    tags.sort();
    tags.dedup();
    tags.join(", ")
}

fn valid_tags_bitmap(entries: &[DispatchEntry]) -> u64 {
    entries
        .iter()
        .fold(0u64, |bits, entry| bits | (1u64 << entry.tag))
}

fn render_valid_tag_fn(out: &mut String, group: &str, entries: &[DispatchEntry]) {
    let upper = group.to_uppercase();
    writeln!(out, "fn is_valid_{group}_tag(tag: i32) -> bool {{").unwrap();
    writeln!(
        out,
        "    tag >= 0 && tag < 64 && (VALID_TAGS_{upper} & (1u64 << tag as u32)) != 0"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    let _ = entries;
    writeln!(out).unwrap();
}

fn render_dispatch_fn<F>(
    out: &mut String,
    fn_name: &str,
    group: &str,
    entries: &[DispatchEntry],
    try_override: &str,
    return_type: &str,
    wrap_body: F,
) where
    F: Fn(&DispatchEntry, &str) -> String,
{
    writeln!(out, "/// Dispatch `{group}` return group by manifest tag.").unwrap();
    writeln!(out, "///").unwrap();
    writeln!(
        out,
        "/// # Safety — `enum_ptr` must reference a valid envelope for the duration of dispatch."
    )
    .unwrap();
    writeln!(
        out,
        "pub unsafe fn {fn_name}(tag: i32, enum_ptr: *const u8) -> {return_type} {{"
    )
    .unwrap();
    writeln!(out, "    if !is_valid_{group}_tag(tag) {{").unwrap();
    match return_type {
        "bool" => writeln!(out, "        return false;").unwrap(),
        _ => writeln!(out, "        return None;").unwrap(),
    }
    writeln!(out, "    }}").unwrap();
    if return_type == "bool" {
        writeln!(
            out,
            "    if unsafe {{ crate::interop::register::{try_override}(tag, enum_ptr) }} {{"
        )
        .unwrap();
        writeln!(out, "        return true;").unwrap();
        writeln!(out, "    }}").unwrap();
    } else {
        writeln!(
            out,
            "    if let Some(value) = unsafe {{ crate::interop::register::{try_override}(tag, enum_ptr) }} {{"
        )
        .unwrap();
        writeln!(out, "        return Some(value);").unwrap();
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out, "    match tag {{").unwrap();
    for entry in entries {
        if entry.is_host() {
            writeln!(
                out,
                "        TAG_{} => {{ crate::interop::register::trap_missing_host_handler(tag) }}",
                tag_const_name(&entry.name)
            )
            .unwrap();
            continue;
        }
        let body = render_dispatch_arm_body(entry, DispatchCallee::Runtime);
        let wrapped = wrap_body(entry, &body);
        writeln!(
            out,
            "        TAG_{} => {{ {wrapped} }}",
            tag_const_name(&entry.name)
        )
        .unwrap();
    }
    match return_type {
        "bool" => writeln!(out, "        _ => false,").unwrap(),
        _ => writeln!(out, "        _ => None,").unwrap(),
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Generate host handler wrappers and registration table for `beskid_host`.
pub fn render_host_handler_table(manifest: &ManifestRoot) -> String {
    let mut out = String::new();
    writeln!(
        &mut out,
        "// @generated by beskid_manifest from runtime_manifest.toml — do not edit."
    )
    .unwrap();
    writeln!(&mut out, "#![allow(clippy::too_many_lines)]").unwrap();
    writeln!(&mut out, "use core::hint::unreachable_unchecked;").unwrap();
    writeln!(&mut out, "use beskid_abi::BeskidStr;").unwrap();
    writeln!(&mut out, "use beskid_runtime::HandlerTableEntry;").unwrap();
    writeln!(&mut out).unwrap();

    let groups: [(&str, &[DispatchEntry], u32); 4] = [
        ("usize", &manifest.dispatch.usize, 0),
        ("ptr", &manifest.dispatch.ptr, 1),
        ("unit", &manifest.dispatch.unit, 2),
        ("i64", &manifest.dispatch.i64, 3),
    ];

    let mut host_entries: Vec<(&str, &DispatchEntry, u32)> = Vec::new();
    for (group, entries, group_id) in &groups {
        for entry in *entries {
            if entry.is_host() {
                host_entries.push((group, entry, *group_id));
            }
        }
    }

    for (group, entry, _) in &host_entries {
        let wrapper = host_wrapper_fn_name(entry);
        let return_type = host_wrapper_return_type(group);
        let enum_param = if entry.params.is_empty() {
            "_enum_ptr"
        } else {
            "enum_ptr"
        };
        let body = render_dispatch_arm_body(entry, DispatchCallee::Host);
        let wrapped = match *group {
            "unit" => format!("{body};"),
            "ptr" if entry.returns == "never" => {
                format!("{body};\n            unreachable_unchecked()")
            }
            "ptr" => format!("{body} as *mut u8"),
            "usize" => format!("{body} as usize"),
            "i64" if entry.returns == "never" => {
                format!("{body};\n            unreachable_unchecked()")
            }
            "i64" => format!("{body} as i64"),
            _ => body,
        };
        writeln!(
            &mut out,
            "unsafe extern \"C\" fn {wrapper}({enum_param}: *const u8) -> {return_type} {{"
        )
        .unwrap();
        writeln!(&mut out, "    unsafe {{").unwrap();
        writeln!(&mut out, "        {wrapped}").unwrap();
        writeln!(&mut out, "    }}").unwrap();
        writeln!(&mut out, "}}").unwrap();
        writeln!(&mut out).unwrap();
    }

    writeln!(
        &mut out,
        "const HOST_HANDLERS: [HandlerTableEntry; {}] = [",
        host_entries.len()
    )
    .unwrap();
    for (_, entry, group_id) in &host_entries {
        let wrapper = host_wrapper_fn_name(entry);
        writeln!(
            &mut out,
            "    HandlerTableEntry {{ group: {group_id}, tag: {}, fn_ptr: {wrapper} as *const u8 }},",
            entry.tag
        )
        .unwrap();
    }
    writeln!(&mut out, "];").unwrap();
    writeln!(&mut out).unwrap();
    writeln!(
        &mut out,
        "/// Register all host dispatch handlers with the language runtime."
    )
    .unwrap();
    writeln!(&mut out, "#[unsafe(no_mangle)]").unwrap();
    writeln!(
        &mut out,
        "pub extern \"C-unwind\" fn beskid_host_register_all() -> i32 {{"
    )
    .unwrap();
    writeln!(&mut out, "    beskid_runtime::beskid_register_handlers(").unwrap();
    writeln!(
        &mut out,
        "        u64::from(beskid_abi::BESKID_RUNTIME_ABI_VERSION),"
    )
    .unwrap();
    writeln!(&mut out, "        HOST_HANDLERS.as_ptr(),").unwrap();
    writeln!(&mut out, "        HOST_HANDLERS.len() as u64,").unwrap();
    writeln!(&mut out, "    )").unwrap();
    writeln!(&mut out, "}}").unwrap();
    out
}

fn host_wrapper_fn_name(entry: &DispatchEntry) -> String {
    format!("host_dispatch_{}", entry.legacy_symbol)
}

fn host_wrapper_return_type(group: &str) -> &'static str {
    match group {
        "usize" => "usize",
        "ptr" => "*mut u8",
        "unit" => "()",
        "i64" => "i64",
        _ => "usize",
    }
}

#[derive(Copy, Clone)]
enum DispatchCallee {
    Runtime,
    Host,
}

fn render_dispatch_arm_body(entry: &DispatchEntry, callee: DispatchCallee) -> String {
    if let Some(body) = special_dispatch_arm(entry, callee) {
        return body;
    }
    let mut decode = String::new();
    for (index, param) in entry.params.iter().enumerate() {
        let offset = 16 + index * 8;
        let var = format!("p{index}");
        writeln!(
            decode,
            "            let {var} = *(enum_ptr.add({offset}) as {});",
            payload_load_type(param)
        )
        .unwrap();
    }
    let args = entry
        .params
        .iter()
        .enumerate()
        .map(|(index, param)| {
            cast_call_arg(&entry.legacy_symbol, param, &format!("p{index}"), index)
        })
        .collect::<Vec<_>>()
        .join(", ");
    let callee = dispatch_callee_path(&entry.legacy_symbol, callee);
    if args.is_empty() {
        format!("{decode}            {callee}()")
    } else {
        format!("{decode}            {callee}({args})")
    }
}

fn dispatch_callee_path(legacy_symbol: &str, callee: DispatchCallee) -> String {
    match callee {
        DispatchCallee::Host => format!("crate::{legacy_symbol}"),
        DispatchCallee::Runtime => match legacy_symbol {
            "channel_receive_ptr"
            | "channel_send_ptr"
            | "channel_try_receive_ptr"
            | "channel_try_send_ptr" => format!("crate::{legacy_symbol}"),
            other => format!("crate::builtins::{other}"),
        },
    }
}

fn special_dispatch_arm(entry: &DispatchEntry, callee: DispatchCallee) -> Option<String> {
    let prefix = match callee {
        DispatchCallee::Host => "crate::",
        DispatchCallee::Runtime => "crate::builtins::",
    };
    match entry.legacy_symbol.as_str() {
        "array_len" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             crate::builtins::array_len(p0 as *const beskid_abi::BeskidArray)"
                .to_string(),
        ),
        "event_subscribe" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
             crate::builtins::event_subscribe(\
                p0 as *mut *mut crate::builtins::EventState, p1 as *mut u8, 256)"
                .to_string(),
        ),
        "event_unsubscribe_first" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
             crate::builtins::event_unsubscribe_first(\
                p0 as *mut *mut crate::builtins::EventState, p1 as *mut u8)"
                .to_string(),
        ),
        "event_len" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             crate::builtins::event_len(p0 as *mut crate::builtins::EventState)"
                .to_string(),
        ),
        "event_get_handler" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             let p1 = *(enum_ptr.add(24) as *const u64);\n\
             crate::builtins::event_get_handler(\
                p0 as *mut crate::builtins::EventState, p1 as usize)"
                .to_string(),
        ),
        "process_exit" => Some(format!(
            "            let p0 = *(enum_ptr.add(16) as *const u64);\n\
             {prefix}process_exit(p0 as i64);"
        )),
        "fiber_spawn" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
             crate::builtins::fiber_spawn(\
                core::mem::transmute(p0), p1 as *mut u8)"
                .to_string(),
        ),
        "fiber_spawn_with_cancel_slot" => Some(
            "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
             let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
             let p2 = *(enum_ptr.add(32) as *const *const u8);\n\
             crate::builtins::fiber_spawn_with_cancel_slot(\
                core::mem::transmute(p0), p1 as *mut u8, p2 as *mut *mut crate::builtins::EventState)"
                .to_string(),
        ),
        "str_concat" | "str_eq" => {
            let symbol = entry.legacy_symbol.clone();
            Some(format!(
                "            let p0 = *(enum_ptr.add(16) as *const *const u8);\n\
                 let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
                 crate::builtins::{symbol}(p0 as *const BeskidStr, p1 as *const BeskidStr)"
            ))
        }
        "channel_receive_ptr" | "channel_try_receive_ptr" => {
            let symbol = entry.legacy_symbol.clone();
            Some(format!(
                "            let p0 = *(enum_ptr.add(16) as *const u64);\n\
                 let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
                 crate::{symbol}(p0 as i64, p1 as *mut *mut u8)"
            ))
        }
        "channel_send_ptr" | "channel_try_send_ptr" => {
            let symbol = entry.legacy_symbol.clone();
            Some(format!(
                "            let p0 = *(enum_ptr.add(16) as *const u64);\n\
                 let p1 = *(enum_ptr.add(24) as *const *const u8);\n\
                 crate::{symbol}(p0 as i64, p1 as *mut u8)"
            ))
        }
        _ => None,
    }
}

fn payload_load_type(param: &str) -> &'static str {
    match param {
        "string" => "*const *const BeskidStr",
        "ptr" => "*const *const u8",
        "usize" => "*const usize",
        "u64" => "*const u64",
        "i64" => "*const i64",
        "i32" => "*const i32",
        _ => "*const u64",
    }
}

fn cast_call_arg(legacy_symbol: &str, param: &str, var: &str, index: usize) -> String {
    match param {
        "string" => format!("{var} as *const BeskidStr"),
        "ptr" => ptr_arg_cast(legacy_symbol, var, index),
        "usize" => match legacy_symbol {
            "array_new" if index == 0 => format!("{var} as usize"),
            "array_new" if index == 1 => format!("{var} as usize"),
            "str_new" if index == 1 => format!("{var} as usize"),
            "dynamic_object_alloc" if index == 0 => format!("{var} as usize"),
            "dynamic_cell_create" | "dynamic_cell_wrap" if index == 0 => {
                format!("{var} as u32")
            }
            "dynamic_cast_checked" if index == 1 => format!("{var} as u32"),
            _ => var.to_string(),
        },
        "u64" | "i64" | "i32" => numeric_arg_cast(legacy_symbol, param, var, index),
        _ => var.to_string(),
    }
}

fn numeric_arg_cast(legacy_symbol: &str, param: &str, var: &str, index: usize) -> String {
    match (legacy_symbol, index) {
        ("str_slice", 1) | ("str_slice", 2) => format!("{var} as usize"),
        ("bytes_set", 1) | ("bytes_set", 2) => format!("{var} as i64"),
        ("dynamic_map_aot", 0)
        | ("dynamic_map_aot", 1)
        | ("dynamic_cast_checked", 1)
        | ("dynamic_cell_create", 0)
        | ("dynamic_cell_wrap", 0) => format!("{var} as u32"),
        _ => match param {
            "u64" if legacy_symbol == "str_slice" && (index == 1 || index == 2) => {
                format!("{var} as usize")
            }
            "i64" => format!("{var} as i64"),
            "i32" => format!("{var} as i32"),
            "u64" => format!("{var} as i64"),
            _ => var.to_string(),
        },
    }
}

fn ptr_arg_cast(legacy_symbol: &str, var: &str, index: usize) -> String {
    match (legacy_symbol, index) {
        ("array_len", 0) => format!("{var} as *const beskid_abi::BeskidArray"),
        ("bytes_from_str", 0) | ("str_from_bytes_utf8", 0) => {
            format!("{var} as *const beskid_abi::BeskidArray")
        }
        ("bytes_compare", 0)
        | ("bytes_compare", 1)
        | ("bytes_copy", 0)
        | ("bytes_copy", 2)
        | ("bytes_get", 0)
        | ("bytes_set", 0)
        | ("syscall_write_bytes", 1) => {
            format!("{var} as *const beskid_abi::BeskidArray")
        }
        ("str_new", 0) => format!("{var} as *const u8"),
        ("str_concat", 0) | ("str_concat", 1) | ("str_eq", 0) | ("str_eq", 1) => {
            format!("{var} as *const BeskidStr")
        }
        ("dynamic_cell_create", 1)
        | ("dynamic_cell_wrap", 1)
        | ("dynamic_map_aot", 2)
        | ("dynamic_map_aot", 3)
        | ("dynamic_map_fallback", 0)
        | ("dynamic_map_fallback", 2)
        | ("dynamic_object_alloc", 0) => format!("{var} as *mut u8"),
        ("dynamic_cast_checked", 0) => format!("{var} as *mut crate::dynamic::DynamicCell"),
        ("channel_receive", 1) | ("channel_try_receive", 1) => format!("{var} as *mut i64"),
        ("fiber_spawn", 1)
        | ("fiber_spawn_with_cancel_slot", 1)
        | ("fiber_spawn_with_cancel_slot", 2) => format!("{var} as *mut u8"),
        ("event_subscribe", 0) => {
            format!("{var} as *mut *mut crate::builtins::EventState")
        }
        ("event_unsubscribe_first", 0) => {
            format!("{var} as *mut *mut crate::builtins::EventState")
        }
        ("event_len", 0) | ("event_get_handler", 0) => {
            format!("{var} as *mut crate::builtins::EventState")
        }
        _ => format!("{var} as *mut u8"),
    }
}

fn format_param_array(params: &[AbiParamKind]) -> String {
    if params.is_empty() {
        return "[]".to_string();
    }
    let inner = params
        .iter()
        .map(|kind| match kind {
            AbiParamKind::Ptr => "AbiParamKind::Ptr",
            AbiParamKind::I64 => "AbiParamKind::I64",
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{inner}]")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn manifest_loads_and_generates() {
        let manifest_path =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../runtime_manifest.toml");
        let manifest = crate::load_manifest(&manifest_path).expect("manifest parse");
        assert_eq!(manifest.manifest.abi_version, 4);
        assert!(!manifest.kernel.is_empty());
        let abi = render_abi_builtins(&manifest);
        assert!(abi.contains("BUILTIN_SPECS"));
        assert!(abi.contains("SYM_ALLOC"));
        let dispatch = render_runtime_dispatch_table(&manifest);
        assert!(dispatch.contains("dispatch_usize"));
        assert!(dispatch.contains("TAG_STR_LEN"));
        assert!(dispatch.contains("VALID_TAGS_USIZE"));
        let symbols = render_abi_symbols(&manifest);
        assert!(symbols.contains("RUNTIME_EXPORT_SYMBOLS"));
        assert!(symbols.contains("SYM_STR_LEN"));
        assert!(!symbols.contains("RUNTIME_EXPORT_SYMBOLS: &[&str] = &[\n    SYM_STR_LEN"));
    }
}
